// Build the Supabase seed files from data/*.json.
//   supabase/seed/01_catalog.sql  global ingredient catalogue + aliases (run once)
//   supabase/seed/02_recipes.sql  imported recipes, loaded into the oldest household (run after signing up)
// Usage: npx tsx scripts/build-seed.ts
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildAliasIndex, matchIngredient } from "../src/lib/catalog";
import type { ImportedRecipe } from "../src/lib/importRecipe";
import { nameKey } from "../src/lib/text";

const ROOT = join(__dirname, "..");
const read = <T>(f: string) => JSON.parse(readFileSync(join(ROOT, "data", f), "utf8")) as T;

type CatalogEntry = { name: string; name_en?: string; aisle: string; pantry?: boolean; ml_per_can?: number; count_unit?: string; equiv?: object; aliases: string[] };
const catalog = read<{ ingredients: CatalogEntry[] }>("catalog.json").ingredients;
const recipes = read<(ImportedRecipe & { slug: string; sourceType: string; error?: string })[]>("recipes.raw.json").filter((r) => !r.error);
// Pictures live in the public "recipe-images" storage bucket (uploaded from data/images/); keep the web URL as a fallback.
const imageFor = (r: { slug: string; image: string | null }) =>
  existsSync(join(ROOT, "data", "images", `${r.slug}.webp`)) ? `storage:recipe-images/${r.slug}.webp` : r.image;
const meta = read<{ recipes: Record<string, { dish_type: string; protein: string; seasons: string[] }> }>("recipe-meta.json").recipes;

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(Math.round(v * 1000) / 1000) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

// ---------- catalogue ----------
// Idempotent: can be re-run after any change of data/catalog.json. Order matters:
// renames, items (insert or update), stale aliases removed, then aliases added (an alias may move to another item).
const renames = existsSync(join(ROOT, "data", "catalog-renames.json"))
  ? (JSON.parse(readFileSync(join(ROOT, "data", "catalog-renames.json"), "utf8")) as Record<string, string>)
  : {};
// Set-based, and every statement self-contained (values inline, no temp or work tables): the Supabase SQL Editor
// keeps nothing from one statement to the next.
const cat: string[] = ["-- Generated by scripts/build-seed.ts. Global ingredient catalogue (idempotent)."];
for (const [from, to] of Object.entries(renames)) {
  cat.push(`update ingredients set name = ${q(to)} where household_id is null and name = ${q(from)} and not exists (select 1 from ingredients x where x.household_id is null and x.name = ${q(to)});`);
}
const items = catalog
  .map((c) => `(${q(c.name)}, ${q(c.aisle)}, ${q(!!c.pantry)}, ${q(c.ml_per_can ?? null)}::numeric, ${q(c.count_unit ?? null)}, ${c.equiv ? `${q(JSON.stringify(c.equiv))}::jsonb` : "null"}, ${q(c.name_en ?? null)})`)
  .join(",\n");
const aliasRows = catalog
  .flatMap((c) => [...new Set(c.aliases.map(nameKey))].map((a) => `(${q(c.name)}, ${q(a)})`))
  .join(",\n");
cat.push(
  // Items: new ones inserted, existing ones updated (the update does not see the rows inserted by the same statement, which are already right).
  `with c(name, aisle, pantry, ml_per_can, count_unit, equiv, name_en) as (values\n${items}\n), added as (insert into ingredients (household_id, name, aisle, pantry, ml_per_can, count_unit, equiv, name_en) select null, c.name, c.aisle, c.pantry, c.ml_per_can, c.count_unit, c.equiv, c.name_en from c where not exists (select 1 from ingredients i where i.household_id is null and i.name = c.name) returning 1)\nupdate ingredients i set aisle = c.aisle, pantry = c.pantry, ml_per_can = c.ml_per_can, count_unit = c.count_unit, equiv = c.equiv, name_en = c.name_en from c where i.household_id is null and i.name = c.name;`,
  // Aliases removed from the catalogue (or moved to another item) go first, then the current ones are added.
  `with c(name, alias) as (values\n${aliasRows}\n)\ndelete from ingredient_aliases a using ingredients i where a.ingredient_id = i.id and a.household_id is null and i.household_id is null and not exists (select 1 from c where c.name = i.name and c.alias = a.alias);`,
  `with c(name, alias) as (values\n${aliasRows}\n)\ninsert into ingredient_aliases (ingredient_id, household_id, alias) select i.id, null, c.alias from c join ingredients i on i.household_id is null and i.name = c.name on conflict do nothing;`,
);

// ---------- recipes ----------
const index = buildAliasIndex(catalog.map((c) => ({ id: c.name, aliases: c.aliases })));
const rec: string[] = [
  "-- Generated by scripts/build-seed.ts. Loads the imported recipes into the first household created.",
  "do $$",
  "declare h uuid := (select id from households order by created_at limit 1); r uuid;",
  "begin",
  "  if h is null then raise exception 'Créez d''abord votre foyer dans l''application.'; end if;",
];
const missingMeta: string[] = [];
for (const r of recipes) {
  const m = meta[r.title];
  if (!m) missingMeta.push(r.title);
  rec.push(
    `  insert into recipes (household_id, title, source_type, source_url, image_url, servings, total_minutes, instructions, dish_type, protein, seasons) values (h, ${q(r.title)}, ${q(r.sourceType)}, ${q(r.sourceUrl)}, ${q(imageFor(r))}, ${q(r.servings)}, ${q(r.totalMinutes)}, ${q(JSON.stringify(r.instructions))}::jsonb, ${q(m?.dish_type ?? null)}, ${q(m?.protein ?? null)}, ${arr(m?.seasons ?? ["printemps", "ete", "automne", "hiver"])}) returning id into r;`,
  );
  r.ingredients.forEach((i, pos) => {
    const match = matchIngredient(i.name, index);
    const ing = match ? `(select id from ingredients where household_id is null and name = ${q(match)})` : "null";
    rec.push(
      `  insert into recipe_ingredients (recipe_id, position, section, raw, quantity, quantity_max, unit, name, note, optional, ingredient_id) values (r, ${pos}, ${q(i.section)}, ${q(i.raw)}, ${q(i.quantity)}, ${q(i.quantityMax)}, ${q(i.unit)}, ${q(i.name)}, ${q(i.note)}, ${q(i.optional)}, ${ing});`,
    );
  });
}
rec.push("end $$;");

mkdirSync(join(ROOT, "supabase", "seed"), { recursive: true });
writeFileSync(join(ROOT, "supabase", "seed", "01_catalog.sql"), cat.join("\n") + "\n");
writeFileSync(join(ROOT, "supabase", "seed", "02_recipes.sql"), rec.join("\n") + "\n");
console.log(`${catalog.length} ingrédients au catalogue, ${recipes.length} recettes`);
if (missingMeta.length) console.log(`Sans catégories : ${missingMeta.join(" | ")}`);
