// Generate a migration that brings households which imported the starter recipes up to date with
// public/starter/recipes.json: catalogue (idempotent seed) + the ingredient lines of every starter recipe.
// Household preferences (seasons, rating, dish type, protein, portions, active) are left untouched.
// Usage: npx tsx scripts/gen-sync.ts <migration-name>   e.g. 0004_sync_ingredients
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..");
const name = process.argv[2];
if (!name) throw new Error("Nom de migration manquant, ex. 0004_sync_ingredients");

type StarterRecipe = {
  title: string;
  source_url: string | null;
  instructions: string[];
  ingredients: {
    position: number;
    section: string | null;
    raw: string;
    quantity: number | null;
    quantity_max: number | null;
    unit: string | null;
    name: string;
    note: string | null;
    optional: boolean;
    catalog: string | null;
  }[];
};
const starter = JSON.parse(readFileSync(join(ROOT, "public", "starter", "recipes.json"), "utf8")) as StarterRecipe[];
const q = (v: unknown) => (v === null || v === undefined ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);

const sql: string[] = [
  `-- ${name}: starter recipes resynchronised with public/starter/recipes.json (generated by scripts/gen-sync.ts).`,
  "",
  readFileSync(join(ROOT, "supabase", "seed", "01_catalog.sql"), "utf8"),
  "begin;",
];
for (const r of starter) {
  const values = r.ingredients
    .map((i) => `(${i.position}, ${q(i.section)}, ${q(i.raw)}, ${q(i.quantity)}, ${q(i.quantity_max)}, ${q(i.unit)}, ${q(i.name)}, ${q(i.note)}, ${i.optional}, ${q(i.catalog)})`)
    .join(",\n  ");
  sql.push(
    `-- ${r.title}`,
    `delete from recipe_ingredients where recipe_id in (select id from recipes where title = ${q(r.title)});`,
    "insert into recipe_ingredients (recipe_id, position, section, raw, quantity, quantity_max, unit, name, note, optional, ingredient_id)",
    "select r.id, v.position, v.section, v.raw, v.quantity::numeric, v.quantity_max::numeric, v.unit, v.name, v.note, v.optional, i.id",
    `from recipes r cross join (values\n  ${values}\n) v(position, section, raw, quantity, quantity_max, unit, name, note, optional, catalog)`,
    `left join ingredients i on i.household_id is null and i.name = v.catalog where r.title = ${q(r.title)};`,
    `update recipes set instructions = ${q(JSON.stringify(r.instructions))}::jsonb${r.source_url ? `, source_url = coalesce(source_url, ${q(r.source_url)})` : ""} where title = ${q(r.title)};`,
  );
}
sql.push("commit;");
writeFileSync(join(ROOT, "supabase", "migrations", `${name}.sql`), sql.join("\n") + "\n");
console.log(`${starter.length} recettes -> supabase/migrations/${name}.sql`);
