-- 0011 (2026-09-30): English version, chosen per household. Recipes are never translated; the interface and the
-- grocery-list names of the catalogue are. Safe to run more than once.
alter table households add column if not exists lang text not null default 'fr' check (lang in ('fr', 'en'));
alter table ingredients add column if not exists name_en text;
update ingredients i set name_en = v.en from (values
('Ail', 'Garlic'),
('Oignon jaune', 'Yellow onion'),
('Oignon rouge', 'Red onion'),
('Oignon vert', 'Green onions'),
('Échalote française', 'Shallot'),
('Gingembre', 'Ginger'),
('Céleri', 'Celery'),
('Carotte', 'Carrot'),
('Aubergine', 'Eggplant'),
('Courgette', 'Zucchini'),
('Courge musquée (butternut)', 'Butternut squash'),
('Chou-fleur', 'Cauliflower'),
('Brocoli', 'Broccoli'),
('Chou de Savoie', 'Savoy cabbage'),
('Chou frisé (kale)', 'Kale'),
('Épinards', 'Spinach'),
('Roquette', 'Arugula'),
('Laitue iceberg', 'Iceberg lettuce'),
('Bok choy', 'Bok choy'),
('Tomate', 'Tomato'),
('Tomates cerises', 'Cherry tomatoes'),
('Concombre', 'Cucumber'),
('Poivron rouge', 'Red bell pepper'),
('Poivron vert', 'Green bell pepper'),
('Piment jalapeño', 'Jalapeño pepper'),
('Piment fort frais', 'Hot chili pepper (fresh)'),
('Patate douce', 'Sweet potato'),
('Pomme de terre', 'Potato'),
('Pomme', 'Apple'),
('Citron', 'Lemon'),
('Lime', 'Lime'),
('Avocat', 'Avocado'),
('Champignons pleurotes', 'Oyster mushrooms'),
('Champignons enoki', 'Enoki mushrooms'),
('Fèves germées', 'Bean sprouts'),
('Coriandre fraîche', 'Cilantro (fresh)'),
('Persil frais', 'Parsley (fresh)'),
('Basilic frais', 'Basil (fresh)'),
('Menthe fraîche', 'Mint (fresh)'),
('Aneth frais', 'Dill (fresh)'),
('Ciboulette', 'Chives'),
('Sauge fraîche', 'Sage (fresh)'),
('Maïs en épi', 'Corn on the cob'),
('Légumes d''accompagnement (au choix)', 'Side vegetables (your choice)'),
('Thym frais', 'Thyme (fresh)'),
('Origan frais', 'Oregano (fresh)'),
('Pousses de luzerne', 'Alfalfa sprouts'),
('Tofu ferme', 'Firm tofu'),
('Tofu extra-ferme', 'Extra-firm tofu'),
('Tofu soyeux', 'Silken tofu'),
('Tempeh', 'Tempeh'),
('Haché végé', 'Plant-based ground round'),
('Beurre végétal', 'Vegan butter'),
('Miso blanc', 'White miso'),
('Nouilles udon', 'Udon noodles'),
('Beurre', 'Butter'),
('Lait', 'Milk'),
('Boisson de soya', 'Soy milk'),
('Boisson végétale', 'Plant-based milk'),
('Crème sure', 'Sour cream'),
('Crème sure végétalienne', 'Vegan sour cream'),
('Yogourt nature', 'Plain yogurt'),
('Crème à cuisson 15 %', 'Cooking cream 15%'),
('Feta', 'Feta'),
('Parmesan', 'Parmesan'),
('Parmesan végane', 'Vegan parmesan'),
('Cheddar fort', 'Old cheddar'),
('Fromage végane râpé', 'Shredded vegan cheese'),
('Œufs', 'Eggs'),
('Hauts de cuisse de poulet désossés', 'Boneless chicken thighs'),
('Tortillas de blé', 'Flour tortillas'),
('Pâte à tarte', 'Pie crust'),
('Croûtons', 'Croutons'),
('Quinoa', 'Quinoa'),
('Orge perlé', 'Pearl barley'),
('Riz à risotto (arborio)', 'Risotto rice (arborio)'),
('Riz à sushi', 'Sushi rice'),
('Riz blanc', 'White rice'),
('Riz sauvage', 'Wild rice'),
('Couscous perlé', 'Pearl couscous'),
('Macaronis', 'Macaroni'),
('Pâtes à lasagne', 'Lasagna noodles'),
('Nouilles ramen', 'Ramen noodles'),
('Lentilles brunes ou vertes (sèches)', 'Brown or green lentils (dried)'),
('Lentilles corail', 'Red lentils'),
('Chapelure panko', 'Panko breadcrumbs'),
('Chapelure', 'Breadcrumbs'),
('Pois chiches (conserve)', 'Chickpeas (canned)'),
('Haricots noirs (conserve)', 'Black beans (canned)'),
('Haricots blancs (conserve)', 'White beans (canned)'),
('Haricots rouges (conserve)', 'Red kidney beans (canned)'),
('Haricots pinto (conserve)', 'Pinto beans (canned)'),
('Lentilles brunes (conserve)', 'Brown lentils (canned)'),
('Tomates en dés (conserve)', 'Diced tomatoes (canned)'),
('Sauce tomate (conserve)', 'Tomato sauce (canned)'),
('Tomates entières (conserve)', 'Whole tomatoes (canned)'),
('Poivrons rouges rôtis (pot)', 'Roasted red peppers (jar)'),
('Pâte de tomate', 'Tomato paste'),
('Tomates séchées', 'Sun-dried tomatoes'),
('Lait de coco', 'Coconut milk'),
('Crème de coco', 'Coconut cream'),
('Bouillon de légumes', 'Vegetable broth'),
('Bouillon aux champignons', 'Mushroom broth'),
('Olives noires', 'Black olives'),
('Câpres', 'Capers'),
('Oignons marinés', 'Pickled onions'),
('Cornichons', 'Pickles'),
('Sauce aux canneberges', 'Cranberry sauce'),
('Champignons séchés', 'Mushrooms (dried)'),
('Pâte de fèves pimentée (doubanjiang)', 'Chili bean paste (doubanjiang)'),
('Feuilles de nori', 'Nori sheets'),
('Sambal oelek', 'Sambal oelek'),
('Huile d''olive', 'Olive oil'),
('Huile végétale', 'Vegetable oil'),
('Huile de coco', 'Coconut oil'),
('Huile d''avocat', 'Avocado oil'),
('Huile de sésame grillé', 'Toasted sesame oil'),
('Huile pimentée (chili croquant)', 'Chili oil (chili crisp)'),
('Sauce soya', 'Soy sauce'),
('Sauce soya foncée', 'Dark soy sauce'),
('Vinaigre de riz', 'Rice vinegar'),
('Vinaigre de vin rouge', 'Red wine vinegar'),
('Vinaigre balsamique', 'Balsamic vinegar'),
('Vinaigre de cidre', 'Apple cider vinegar'),
('Moutarde de Dijon', 'Dijon mustard'),
('Moutarde à l''ancienne', 'Grainy mustard'),
('Mayonnaise', 'Mayonnaise'),
('Mayonnaise végétalienne (Vegenaise)', 'Vegan mayonnaise (Vegenaise)'),
('Harissa', 'Harissa'),
('Sauce piquante', 'Hot sauce'),
('Sauce piri-piri', 'Piri-piri sauce'),
('Sauce barbecue', 'Barbecue sauce'),
('Sauce Worcestershire', 'Worcestershire sauce'),
('Sirop d''érable', 'Maple syrup'),
('Miel', 'Honey'),
('Beurre d''arachide', 'Peanut butter'),
('Beurre d''amande ou de cajou', 'Almond or cashew butter'),
('Tahini', 'Tahini'),
('Farine tout usage', 'All-purpose flour'),
('Fécule de maïs', 'Cornstarch'),
('Cassonade', 'Brown sugar'),
('Sucre', 'Sugar'),
('Levure alimentaire', 'Nutritional yeast'),
('Sel', 'Salt'),
('Poivre noir', 'Black pepper'),
('Poudre d''ail', 'Garlic powder'),
('Poudre d''oignon', 'Onion powder'),
('Paprika', 'Paprika'),
('Paprika fumé', 'Smoked paprika'),
('Cumin moulu', 'Ground cumin'),
('Graines de cumin', 'Cumin seeds'),
('Graines de fenouil', 'Fennel seeds'),
('Coriandre moulue', 'Ground coriander'),
('Graines de coriandre', 'Coriander seeds'),
('Curcuma', 'Turmeric'),
('Garam masala', 'Garam masala'),
('Cari', 'Curry powder'),
('Cannelle', 'Cinnamon'),
('Muscade', 'Nutmeg'),
('Piment de la Jamaïque', 'Allspice'),
('Piment de Cayenne', 'Cayenne pepper'),
('Piment gochugaru', 'Gochugaru (Korean chili flakes)'),
('Flocons de piment fort', 'Red pepper flakes'),
('Assaisonnement au chili', 'Chili powder'),
('Moutarde en poudre', 'Mustard powder'),
('Feuilles de laurier', 'Bay leaves'),
('Thym séché', 'Thyme (dried)'),
('Origan séché', 'Oregano (dried)'),
('Basilic séché', 'Basil (dried)'),
('Persil séché', 'Parsley (dried)'),
('Romarin séché', 'Rosemary (dried)'),
('Fines herbes italiennes', 'Italian seasoning'),
('Arachides rôties', 'Roasted peanuts'),
('Amandes', 'Almonds'),
('Noix de Grenoble', 'Walnuts'),
('Noix de macadamia', 'Macadamia nuts'),
('Graines de citrouille', 'Pumpkin seeds'),
('Graines de sésame grillées', 'Toasted sesame seeds'),
('Croustilles de maïs', 'Tortilla chips'),
('Édamames', 'Edamame'),
('Petits pois surgelés', 'Peas (frozen)'),
('Maïs en grains', 'Corn kernels'),
('Vin blanc', 'White wine'),
('Poireau', 'Leek'),
('Champignons blancs', 'White mushrooms'),
('Champignons shiitakes', 'Shiitake mushrooms'),
('Chou rouge', 'Red cabbage'),
('Radis', 'Radishes'),
('Laitue romaine', 'Romaine lettuce'),
('Mesclun', 'Mixed greens'),
('Grenade', 'Pomegranate'),
('Pêches', 'Peaches'),
('Fines herbes fraîches (au choix)', 'Fresh herbs (your choice)'),
('Halloumi', 'Halloumi'),
('Mozzarella fraîche', 'Mozzarella (fresh)'),
('Fromage de chèvre', 'Goat cheese'),
('Yogourt de soya', 'Soy yogurt'),
('Crème végétale à cuisson (Belsoy)', 'Plant-based cooking cream (Belsoy)'),
('Houmous', 'Hummus'),
('Pesto', 'Pesto'),
('Pains naan', 'Naan breads'),
('Pains plats (pita)', 'Flatbreads (pita)'),
('Pain de campagne (levain)', 'Country bread (sourdough)'),
('Pâtes courtes', 'Short pasta'),
('Nouilles asiatiques (soba, orientales)', 'Asian noodles (soba, oriental)'),
('Purée de citrouille', 'Pumpkin purée'),
('Maïs en crème (conserve)', 'Creamed corn (canned)'),
('Bouillon de poulet', 'Chicken broth'),
('Olives vertes', 'Green olives'),
('Thon en conserve', 'Canned tuna'),
('Chipotle en sauce adobo', 'Chipotle peppers in adobo sauce'),
('Sauce hoisin', 'Hoisin sauce'),
('Pâte de cari rouge', 'Red curry paste'),
('Nouilles de riz', 'Rice noodles'),
('Gochujang', 'Gochujang'),
('Sauce aux huîtres végétale (champignons)', 'Vegetarian oyster sauce (mushroom)'),
('Sauce aux huîtres', 'Oyster sauce'),
('Sauce de poisson', 'Fish sauce'),
('Vinaigre blanc', 'White vinegar'),
('Graines de moutarde', 'Mustard seeds'),
('Épices à tourtière', 'Tourtière spice'),
('Sumac', 'Sumac'),
('Herbes de Provence', 'Herbes de Provence'),
('Assaisonnement cajun', 'Cajun seasoning'),
('Assaisonnement à tacos', 'Taco seasoning'),
('Pistaches', 'Pistachios'),
('Noix de cajou', 'Cashews'),
('Noix de pin', 'Pine nuts'),
('Graines de tournesol', 'Sunflower seeds'),
('Raisins secs', 'Raisins'),
('Canneberges séchées', 'Cranberries (dried)'),
('Noix mélangées', 'Mixed nuts'),
('Croustilles de pita', 'Pita chips'),
('Eau', 'Water')
) v(name, en) where i.household_id is null and i.name = v.name;
