-- 0013 (2026-09-30): catalogue aliases after 0012 (run 0012 first). Safe to run more than once.
with c(name, alias) as (values
('Ail', 'ail'),
('Ail', 'garlic'),
('Ail', 'garlic cloves'),
('Ail', 'ail hache'),
('Ail', 'ail entieres'),
('Ail', 'gousse d ail'),
('Ail', 'gousses d ail'),
('Ail', 'tete d ail'),
('Ail', 'tetes d ail'),
('Oignon jaune', 'oignon'),
('Oignon jaune', 'oignons'),
('Oignon jaune', 'oignon jaune'),
('Oignon jaune', 'oignons jaunes'),
('Oignon jaune', 'onion'),
('Oignon jaune', 'onions'),
('Oignon jaune', 'yellow onion'),
('Oignon rouge', 'oignon rouge'),
('Oignon rouge', 'oignons rouges'),
('Oignon rouge', 'red onion'),
('Oignon rouge', 'red onions'),
('Oignon vert', 'oignon vert'),
('Oignon vert', 'oignons verts'),
('Oignon vert', 'green onion'),
('Oignon vert', 'green onions'),
('Oignon vert', 'green oignons'),
('Oignon vert', 'spring onion'),
('Oignon vert', 'spring onions'),
('Oignon vert', 'scallion'),
('Oignon vert', 'scallions'),
('Oignon vert', 'echalote verte'),
('Échalote française', 'echalote francaise'),
('Échalote française', 'echalotes francaises'),
('Échalote française', 'echalote'),
('Échalote française', 'shallot'),
('Échalote française', 'shallots'),
('Gingembre', 'gingembre'),
('Gingembre', 'gingembre frais'),
('Gingembre', 'ginger'),
('Gingembre', 'ginger root'),
('Céleri', 'celeri'),
('Céleri', 'celery'),
('Carotte', 'carotte'),
('Carotte', 'carottes'),
('Carotte', 'carrot'),
('Carotte', 'carrots'),
('Aubergine', 'aubergine'),
('Aubergine', 'aubergines'),
('Aubergine', 'eggplant'),
('Courgette', 'courgette'),
('Courgette', 'courgettes'),
('Courgette', 'zucchini'),
('Courge musquée (butternut)', 'courge musquee'),
('Courge musquée (butternut)', 'courge butternut'),
('Courge musquée (butternut)', 'butternut squash'),
('Courge musquée (butternut)', 'butternut'),
('Chou-fleur', 'chou fleur'),
('Chou-fleur', 'cauliflower'),
('Brocoli', 'brocoli'),
('Brocoli', 'broccoli'),
('Brocoli', 'couronne de brocoli'),
('Brocoli', 'couronnes de brocoli'),
('Chou de Savoie', 'chou de savoie'),
('Chou de Savoie', 'savoy cabbage'),
('Chou frisé (kale)', 'kale'),
('Chou frisé (kale)', 'chou frise'),
('Épinards', 'epinards'),
('Épinards', 'bebes epinards'),
('Épinards', 'spinach'),
('Épinards', 'baby spinach'),
('Roquette', 'roquette'),
('Roquette', 'arugula'),
('Laitue iceberg', 'laitue iceberg'),
('Laitue iceberg', 'iceberg lettuce'),
('Bok choy', 'bok choy'),
('Bok choy', 'baby bok choy'),
('Bok choy', 'pak choi'),
('Tomate', 'tomate'),
('Tomate', 'tomates'),
('Tomate', 'tomato'),
('Tomate', 'tomatoes'),
('Tomates cerises', 'tomates cerises'),
('Tomates cerises', 'cherry tomatoes'),
('Tomates cerises', 'grape tomatoes'),
('Concombre', 'concombre'),
('Concombre', 'concombres'),
('Concombre', 'cucumber'),
('Concombre', 'cucumbers'),
('Poivron rouge', 'poivron'),
('Poivron rouge', 'poivrons'),
('Poivron rouge', 'poivron rouge'),
('Poivron rouge', 'poivrons rouges'),
('Poivron rouge', 'red bell pepper'),
('Poivron rouge', 'bell pepper'),
('Poivron rouge', 'red pepper'),
('Poivron rouge', 'red peppers'),
('Poivron rouge', 'red bell peppers'),
('Poivron vert', 'poivron vert'),
('Poivron vert', 'poivrons verts'),
('Poivron vert', 'green bell pepper'),
('Poivron vert', 'green pepper'),
('Poivron vert', 'green bell peppers'),
('Poivron vert', 'green peppers'),
('Piment jalapeño', 'piment jalapeno'),
('Piment jalapeño', 'jalapeno'),
('Piment fort frais', 'long green chili pepper'),
('Piment fort frais', 'green chili'),
('Piment fort frais', 'piment vert'),
('Piment fort frais', 'serrano pepper'),
('Piment fort frais', 'piment serrano'),
('Piment fort frais', 'red chilli'),
('Piment fort frais', 'red chili'),
('Piment fort frais', 'piment chili rouge'),
('Piment fort frais', 'piment rouge'),
('Piment fort frais', 'piments chili'),
('Piment fort frais', 'piment chili'),
('Piment fort frais', 'chilli'),
('Piment fort frais', 'chili pepper'),
('Piment fort frais', 'scotch bonnet'),
('Piment fort frais', 'scotch bonnet pepper'),
('Piment fort frais', 'habanero'),
('Piment fort frais', 'piment habanero'),
('Patate douce', 'patate douce'),
('Patate douce', 'patates douces'),
('Patate douce', 'sweet potato'),
('Patate douce', 'sweet potatoes'),
('Pomme de terre', 'pomme de terre'),
('Pomme de terre', 'pommes de terre'),
('Pomme de terre', 'potato'),
('Pomme de terre', 'potatoes'),
('Pomme', 'pomme'),
('Pomme', 'pommes'),
('Pomme', 'apple'),
('Pomme', 'apples'),
('Citron', 'citron'),
('Citron', 'citrons'),
('Citron', 'lemon'),
('Citron', 'lemons'),
('Citron', 'jus de citron'),
('Citron', 'lemon juice'),
('Lime', 'lime'),
('Lime', 'limes'),
('Lime', 'jus de lime'),
('Lime', 'lime juice'),
('Lime', 'citron vert'),
('Avocat', 'avocat'),
('Avocat', 'avocats'),
('Avocat', 'avocado'),
('Avocat', 'avocados'),
('Avocat', 'guacamole'),
('Avocat', 'lazy guacamole'),
('Champignons pleurotes', 'champignons pleurotes'),
('Champignons pleurotes', 'pleurotes'),
('Champignons pleurotes', 'oyster mushrooms'),
('Champignons enoki', 'champignons enokis'),
('Champignons enoki', 'champignons enoki'),
('Champignons enoki', 'enoki'),
('Champignons enoki', 'enoki mushrooms'),
('Fèves germées', 'feves germees'),
('Fèves germées', 'bean sprouts'),
('Coriandre fraîche', 'coriandre'),
('Coriandre fraîche', 'coriandre fraiche'),
('Coriandre fraîche', 'feuilles de coriandre'),
('Coriandre fraîche', 'cilantro'),
('Coriandre fraîche', 'fresh cilantro'),
('Coriandre fraîche', 'fresh coriander'),
('Persil frais', 'persil'),
('Persil frais', 'persil italien'),
('Persil frais', 'persil plat'),
('Persil frais', 'parsley'),
('Persil frais', 'fresh parsley'),
('Basilic frais', 'basilic'),
('Basilic frais', 'feuilles de basilic'),
('Basilic frais', 'basil'),
('Basilic frais', 'fresh basil'),
('Basilic frais', 'fresh basil leaves'),
('Menthe fraîche', 'menthe'),
('Menthe fraîche', 'feuilles de menthe'),
('Menthe fraîche', 'fresh mint'),
('Menthe fraîche', 'fresh mint leaves'),
('Menthe fraîche', 'menthe fraiche'),
('Menthe fraîche', 'mint leaves'),
('Aneth frais', 'aneth'),
('Aneth frais', 'dill'),
('Ciboulette', 'ciboulette'),
('Ciboulette', 'chives'),
('Sauge fraîche', 'sauge'),
('Sauge fraîche', 'feuilles de sauge'),
('Sauge fraîche', 'sage'),
('Sauge fraîche', 'sauge fraiche'),
('Sauge fraîche', 'fresh sage'),
('Sauge fraîche', 'fresh sage leaves'),
('Sauge fraîche', 'sage leaves'),
('Maïs en épi', 'epi de mais'),
('Maïs en épi', 'epis de mais'),
('Maïs en épi', 'mais en epi'),
('Maïs en épi', 'corn on the cob'),
('Maïs en épi', 'ears of corn'),
('Légumes d''accompagnement (au choix)', 'legumes pour accompagner le tofu'),
('Légumes d''accompagnement (au choix)', 'legumes pour accompagner'),
('Légumes d''accompagnement (au choix)', 'legumes d accompagnement'),
('Légumes d''accompagnement (au choix)', 'legumes au choix'),
('Thym frais', 'thym frais'),
('Thym frais', 'fresh thyme'),
('Thym frais', 'branches de thym'),
('Thym frais', 'thyme sprigs'),
('Thym frais', 'thyme sprig'),
('Thym frais', 'sprigs of thyme'),
('Thym frais', 'sprigs thyme'),
('Thym frais', 'fresh thyme sprigs'),
('Thym frais', 'brins de thym'),
('Thym frais', 'branche de thym'),
('Origan frais', 'origan frais'),
('Origan frais', 'fresh oregano'),
('Pousses de luzerne', 'luzerne'),
('Pousses de luzerne', 'alfalfa sprouts'),
('Tofu ferme', 'tofu'),
('Tofu ferme', 'tofu ferme'),
('Tofu ferme', 'firm tofu'),
('Tofu ferme', 'sofritas'),
('Tofu extra-ferme', 'tofu extra ferme'),
('Tofu extra-ferme', 'extra firm tofu'),
('Tofu soyeux', 'tofu soyeux'),
('Tofu soyeux', 'silken tofu'),
('Tempeh', 'tempeh'),
('Haché végé', 'vegan mince'),
('Haché végé', 'hache vege'),
('Haché végé', 'hache vegetal'),
('Beurre végétal', 'vegan butter'),
('Beurre végétal', 'beurre vegetal'),
('Beurre végétal', 'margarine'),
('Miso blanc', 'miso'),
('Miso blanc', 'white miso paste'),
('Miso blanc', 'miso blanc'),
('Miso blanc', 'pate miso'),
('Nouilles udon', 'udon noodles'),
('Nouilles udon', 'nouilles udon'),
('Nouilles udon', 'udon'),
('Beurre', 'beurre'),
('Beurre', 'beurre non sale'),
('Beurre', 'butter'),
('Beurre', 'unsalted butter'),
('Lait', 'lait'),
('Lait', 'milk'),
('Boisson végétale', 'lait vegetal'),
('Boisson végétale', 'boisson vegetale'),
('Boisson végétale', 'plant milk'),
('Boisson végétale', 'oat milk'),
('Boisson végétale', 'lait d amande'),
('Boisson végétale', 'almond milk'),
('Boisson végétale', 'lait de riz'),
('Boisson végétale', 'rice milk'),
('Boisson végétale', 'lait d avoine'),
('Boisson végétale', 'lait de cajou'),
('Boisson végétale', 'cashew milk'),
('Boisson végétale', 'boisson d avoine'),
('Boisson végétale', 'boisson d amande'),
('Boisson végétale', 'boisson de soya'),
('Boisson végétale', 'lait de soya'),
('Boisson végétale', 'soy milk'),
('Crème sure', 'creme sure'),
('Crème sure', 'sour cream'),
('Crème sure végétalienne', 'creme sure vegetalienne'),
('Crème sure végétalienne', 'vegan sour cream'),
('Yogourt nature', 'yogourt'),
('Yogourt nature', 'yogourt nature'),
('Yogourt nature', 'plain yogurt'),
('Crème à cuisson 15 %', 'creme a cuisson'),
('Crème à cuisson 15 %', 'cooking cream'),
('Feta', 'feta'),
('Feta', 'fromage feta'),
('Feta', 'feta cheese'),
('Parmesan', 'parmesan'),
('Parmesan', 'parmigiano'),
('Parmesan végane', 'vegan parmesan'),
('Parmesan végane', 'parmesan vegane'),
('Parmesan végane', 'vegan parm'),
('Parmesan végane', 'parmesan vegetal'),
('Parmesan végane', 'parmesan vegan'),
('Parmesan végane', 'parmesan vegetalien'),
('Parmesan végane', 'parmesan vegetalienne'),
('Cheddar fort', 'cheddar'),
('Cheddar fort', 'cheddar fort'),
('Fromage végane râpé', 'grated vegan cheese'),
('Fromage végane râpé', 'vegan cheese'),
('Fromage végane râpé', 'fromage vegetalien'),
('Fromage végane râpé', 'vegan feta'),
('Fromage végane râpé', 'vegan cheddar'),
('Fromage végane râpé', 'fromage vegane'),
('Fromage végane râpé', 'feta vegetalienne'),
('Fromage végane râpé', 'feta vegane'),
('Fromage végane râpé', 'cheddar vegetalien'),
('Fromage végane râpé', 'cheddar vegane'),
('Fromage végane râpé', 'fromage vegetal'),
('Fromage végane râpé', 'vegan mozzarella'),
('Fromage végane râpé', 'mozzarella vegetalienne'),
('Œufs', 'oeuf'),
('Œufs', 'oeufs'),
('Œufs', 'egg'),
('Œufs', 'eggs'),
('Hauts de cuisse de poulet désossés', 'hauts de cuisse de poulet'),
('Hauts de cuisse de poulet désossés', 'chicken thighs'),
('Tortillas de blé', 'tortilla'),
('Tortillas de blé', 'tortillas'),
('Tortillas de blé', 'tortillas de ble'),
('Tortillas de blé', 'tortilla de ble'),
('Tortillas de blé', 'flour tortillas'),
('Tortillas de blé', 'soft flour tortillas'),
('Tortillas de blé', 'small soft flour tortillas'),
('Tortillas de blé', 'tortillas de farine'),
('Pâte à tarte', 'pate a tarte'),
('Pâte à tarte', 'pates a tarte'),
('Pâte à tarte', 'abaisse'),
('Pâte à tarte', 'abaisses'),
('Pâte à tarte', 'pie crust'),
('Pâte à tarte', 'pie dough'),
('Croûtons', 'croutons'),
('Quinoa', 'quinoa'),
('Orge perlé', 'orge'),
('Orge perlé', 'orge perle'),
('Orge perlé', 'barley'),
('Orge perlé', 'pearl barley'),
('Riz à risotto (arborio)', 'riz a risotto'),
('Riz à risotto (arborio)', 'arborio'),
('Riz à sushi', 'riz a sushi'),
('Riz à sushi', 'sushi rice'),
('Riz blanc', 'riz'),
('Riz blanc', 'riz blanc'),
('Riz blanc', 'white rice'),
('Riz blanc', 'rice'),
('Riz blanc', 'feculents'),
('Riz blanc', 'feculents au choix'),
('Riz blanc', 'riz basmati'),
('Riz blanc', 'basmati rice'),
('Riz blanc', 'riz jasmin'),
('Riz sauvage', 'riz sauvage'),
('Riz sauvage', 'wild rice'),
('Couscous perlé', 'couscous perle'),
('Couscous perlé', 'pearl couscous'),
('Macaronis', 'macaroni'),
('Macaronis', 'macaronis'),
('Pâtes à lasagne', 'lasagnes'),
('Pâtes à lasagne', 'pates a lasagne'),
('Pâtes à lasagne', 'lasagna sheets'),
('Pâtes à lasagne', 'dried lasagna sheets'),
('Nouilles ramen', 'nouilles ramen'),
('Nouilles ramen', 'ramen noodles'),
('Nouilles ramen', 'nouilles instantanees'),
('Lentilles brunes ou vertes (sèches)', 'lentilles brunes seches'),
('Lentilles brunes ou vertes (sèches)', 'lentilles vertes seches'),
('Lentilles brunes ou vertes (sèches)', 'lentilles seches'),
('Lentilles brunes ou vertes (sèches)', 'dried brown lentils'),
('Lentilles brunes ou vertes (sèches)', 'dried green lentils'),
('Lentilles brunes ou vertes (sèches)', 'dried lentils'),
('Lentilles brunes ou vertes (sèches)', 'lentilles vertes'),
('Lentilles brunes ou vertes (sèches)', 'lentilles du puy'),
('Lentilles brunes ou vertes (sèches)', 'green lentils'),
('Lentilles brunes ou vertes (sèches)', 'french lentils'),
('Lentilles corail', 'lentilles corail'),
('Lentilles corail', 'red lentils'),
('Lentilles corail', 'red split lentils'),
('Lentilles corail', 'lentilles rouges'),
('Chapelure panko', 'chapelure panko'),
('Chapelure panko', 'panko'),
('Chapelure', 'chapelure'),
('Chapelure', 'chapelure italienne'),
('Chapelure', 'breadcrumbs'),
('Pois chiches (conserve)', 'pois chiche'),
('Pois chiches (conserve)', 'pois chiches'),
('Pois chiches (conserve)', 'chickpeas'),
('Pois chiches (conserve)', 'cooked chickpeas'),
('Haricots noirs (conserve)', 'haricots noirs'),
('Haricots noirs (conserve)', 'black beans'),
('Haricots blancs (conserve)', 'haricot blanc'),
('Haricots blancs (conserve)', 'haricots blancs'),
('Haricots blancs (conserve)', 'white beans'),
('Haricots blancs (conserve)', 'white kidney beans'),
('Haricots blancs (conserve)', 'cannellini'),
('Haricots blancs (conserve)', 'cannellini beans'),
('Haricots blancs (conserve)', 'haricots cannellini'),
('Haricots rouges (conserve)', 'haricots rouges'),
('Haricots rouges (conserve)', 'kidney beans'),
('Haricots rouges (conserve)', 'cooked kidney beans'),
('Haricots pinto (conserve)', 'haricots pinto'),
('Haricots pinto (conserve)', 'pinto beans'),
('Haricots pinto (conserve)', 'cooked pinto beans'),
('Lentilles brunes (conserve)', 'lentilles brunes'),
('Lentilles brunes (conserve)', 'cooked brown lentils'),
('Lentilles brunes (conserve)', 'brown lentils'),
('Lentilles brunes (conserve)', 'lentils'),
('Lentilles brunes (conserve)', 'canned lentils'),
('Lentilles brunes (conserve)', 'lentilles en conserve'),
('Lentilles brunes (conserve)', 'lentilles cuites'),
('Lentilles brunes (conserve)', 'cooked lentils'),
('Lentilles brunes (conserve)', 'lentilles vertes en conserve'),
('Tomates en dés (conserve)', 'tomates en des'),
('Tomates en dés (conserve)', 'tomates concassees'),
('Tomates en dés (conserve)', 'chopped tomatoes'),
('Tomates en dés (conserve)', 'diced tomatoes'),
('Sauce tomate (conserve)', 'sauce tomate'),
('Sauce tomate (conserve)', 'tomato sauce'),
('Sauce tomate (conserve)', 'passata'),
('Sauce tomate (conserve)', 'coulis de tomates'),
('Sauce tomate (conserve)', 'tomates broyees'),
('Sauce tomate (conserve)', 'crushed tomatoes'),
('Tomates entières (conserve)', 'whole peeled tomatoes'),
('Tomates entières (conserve)', 'peeled tomatoes'),
('Tomates entières (conserve)', 'tomates entieres'),
('Tomates entières (conserve)', 'tomates entieres pelees'),
('Tomates entières (conserve)', 'tomates pelees'),
('Tomates entières (conserve)', 'tomates en conserve'),
('Tomates entières (conserve)', 'canned tomatoes'),
('Tomates entières (conserve)', 'tinned tomatoes'),
('Poivrons rouges rôtis (pot)', 'poivrons rouges rotis'),
('Poivrons rouges rôtis (pot)', 'poivron rouge roti'),
('Poivrons rouges rôtis (pot)', 'poivrons rotis'),
('Poivrons rouges rôtis (pot)', 'roasted red peppers'),
('Poivrons rouges rôtis (pot)', 'roasted red pepper'),
('Pâte de tomate', 'pate de tomate'),
('Pâte de tomate', 'pate de tomates'),
('Pâte de tomate', 'tomato paste'),
('Pâte de tomate', 'tomato puree'),
('Tomates séchées', 'tomates sechees'),
('Tomates séchées', 'sun dried tomatoes'),
('Tomates séchées', 'sundried tomatoes'),
('Tomates séchées', 'sundried tomato'),
('Lait de coco', 'lait de coco'),
('Lait de coco', 'coconut milk'),
('Lait de coco', 'lait de coconut'),
('Crème de coco', 'creme de coco'),
('Crème de coco', 'coconut cream'),
('Bouillon de légumes', 'bouillon de legumes'),
('Bouillon de légumes', 'vegetable stock'),
('Bouillon de légumes', 'vegetable broth'),
('Bouillon de légumes', 'vegetable stock cube'),
('Bouillon de légumes', 'cube de bouillon'),
('Bouillon aux champignons', 'bouillon aux champignons'),
('Bouillon aux champignons', 'mushroom broth'),
('Olives noires', 'olives noires'),
('Olives noires', 'black olives'),
('Câpres', 'capres'),
('Câpres', 'capers'),
('Oignons marinés', 'oignons marines'),
('Oignons marinés', 'oignon marine'),
('Oignons marinés', 'pickled onions'),
('Oignons marinés', 'pickled red onions'),
('Oignons marinés', 'oignons rouges marines'),
('Cornichons', 'cornichons'),
('Cornichons', 'pickles'),
('Sauce aux canneberges', 'sauce aux canneberges'),
('Sauce aux canneberges', 'cranberry sauce'),
('Champignons séchés', 'champignons seches'),
('Champignons séchés', 'champignons forestiers seches'),
('Champignons séchés', 'dried mushrooms'),
('Pâte de fèves pimentée (doubanjiang)', 'doubanjiang'),
('Feuilles de nori', 'nori'),
('Feuilles de nori', 'nori sheets'),
('Feuilles de nori', 'feuilles de nori'),
('Sambal oelek', 'sambal oelek'),
('Sambal oelek', 'puree de piment'),
('Sambal oelek', 'chili paste'),
('Huile d''olive', 'huile d olive'),
('Huile d''olive', 'olive oil'),
('Huile végétale', 'huile'),
('Huile végétale', 'oil'),
('Huile végétale', 'huile vegetale'),
('Huile végétale', 'vegetable oil'),
('Huile végétale', 'huile de canola'),
('Huile végétale', 'canola oil'),
('Huile de coco', 'huile de coco'),
('Huile de coco', 'coconut oil'),
('Huile d''avocat', 'huile d avocat'),
('Huile d''avocat', 'avocado oil'),
('Huile de sésame grillé', 'huile de sesame'),
('Huile de sésame grillé', 'sesame oil'),
('Huile de sésame grillé', 'toasted sesame oil'),
('Huile pimentée (chili croquant)', 'chili oil'),
('Huile pimentée (chili croquant)', 'chilli oil'),
('Huile pimentée (chili croquant)', 'chili crisp oil'),
('Huile pimentée (chili croquant)', 'chili croquant'),
('Huile pimentée (chili croquant)', 'huile piquante'),
('Huile pimentée (chili croquant)', 'huile pimentee'),
('Huile pimentée (chili croquant)', 'chili crisp'),
('Huile pimentée (chili croquant)', 'huile epicee'),
('Sauce soya', 'sauce soya'),
('Sauce soya', 'sauce soja'),
('Sauce soya', 'soy sauce'),
('Sauce soya', 'light soy sauce'),
('Sauce soya', 'reduced sodium soy sauce'),
('Sauce soya', 'sodium reduced soy sauce'),
('Sauce soya', 'tamari'),
('Sauce soya foncée', 'dark soy sauce'),
('Sauce soya foncée', 'sauce soya foncee'),
('Vinaigre de riz', 'vinaigre de riz'),
('Vinaigre de riz', 'rice vinegar'),
('Vinaigre de riz', 'vinaigre riz'),
('Vinaigre de riz', 'rice wine vinegar'),
('Vinaigre de riz', 'vinaigre de vin de riz'),
('Vinaigre de vin rouge', 'vinaigre de vin'),
('Vinaigre de vin rouge', 'vinaigre de vin rouge'),
('Vinaigre de vin rouge', 'red wine vinegar'),
('Vinaigre balsamique', 'vinaigre balsamique'),
('Vinaigre balsamique', 'balsamic vinegar'),
('Vinaigre de cidre', 'vinaigre de cidre'),
('Vinaigre de cidre', 'apple cider vinegar'),
('Moutarde de Dijon', 'moutarde de dijon'),
('Moutarde de Dijon', 'dijon mustard'),
('Moutarde à l''ancienne', 'moutarde a l ancienne'),
('Moutarde à l''ancienne', 'wholegrain mustard'),
('Mayonnaise', 'mayonnaise'),
('Mayonnaise', 'mayo'),
('Mayonnaise végétalienne (Vegenaise)', 'vegenaise'),
('Mayonnaise végétalienne (Vegenaise)', 'mayonnaise vegetalienne'),
('Mayonnaise végétalienne (Vegenaise)', 'vegan mayo'),
('Mayonnaise végétalienne (Vegenaise)', 'vegan mayonnaise'),
('Harissa', 'harissa'),
('Harissa', 'pate harissa'),
('Harissa', 'pate de harissa'),
('Sauce piquante', 'sauce piquante'),
('Sauce piquante', 'hot sauce'),
('Sauce piquante', 'sriracha'),
('Sauce piri-piri', 'sauce piri piri'),
('Sauce piri-piri', 'piri piri sauce'),
('Sauce barbecue', 'sauce bbq'),
('Sauce barbecue', 'bbq sauce'),
('Sauce barbecue', 'sauce barbecue'),
('Sauce Worcestershire', 'sauce worcestershire'),
('Sauce Worcestershire', 'worcestershire sauce'),
('Sirop d''érable', 'sirop d erable'),
('Sirop d''érable', 'maple syrup'),
('Miel', 'miel'),
('Miel', 'honey'),
('Beurre d''arachide', 'beurre d arachide'),
('Beurre d''arachide', 'peanut butter'),
('Beurre d''amande ou de cajou', 'beurre d amande'),
('Beurre d''amande ou de cajou', 'beurre de cajou'),
('Beurre d''amande ou de cajou', 'beurre de noix de cajou'),
('Beurre d''amande ou de cajou', 'almond butter'),
('Beurre d''amande ou de cajou', 'cashew butter'),
('Tahini', 'tahini'),
('Tahini', 'tahin'),
('Tahini', 'sesame paste'),
('Farine tout usage', 'farine'),
('Farine tout usage', 'farine tout usage'),
('Farine tout usage', 'farine blanche tout usage'),
('Farine tout usage', 'flour'),
('Farine tout usage', 'all purpose flour'),
('Fécule de maïs', 'fecule de mais'),
('Fécule de maïs', 'cornstarch'),
('Fécule de maïs', 'corn starch'),
('Fécule de maïs', 'fecule'),
('Cassonade', 'cassonade'),
('Cassonade', 'brown sugar'),
('Cassonade', 'sucre brun'),
('Cassonade', 'light brown sugar'),
('Cassonade', 'dark brown sugar'),
('Sucre', 'sucre'),
('Sucre', 'sugar'),
('Sucre', 'cane sugar'),
('Sucre', 'sucre de canne'),
('Levure alimentaire', 'levure alimentaire'),
('Levure alimentaire', 'levure nutritionnelle'),
('Levure alimentaire', 'nutritional yeast'),
('Sel', 'sel'),
('Sel', 'salt'),
('Sel', 'sea salt'),
('Sel', 'sel casher'),
('Sel', 'kosher salt'),
('Sel', 'sel et poivre'),
('Poivre noir', 'poivre'),
('Poivre noir', 'poivre noir'),
('Poivre noir', 'poivre du moulin'),
('Poivre noir', 'pepper'),
('Poivre noir', 'black pepper'),
('Poivre noir', 'ground black pepper'),
('Poivre noir', 'cracked black pepper'),
('Poivre noir', 'black pepper corns'),
('Poudre d''ail', 'poudre d ail'),
('Poudre d''ail', 'garlic powder'),
('Poudre d''oignon', 'poudre d oignon'),
('Poudre d''oignon', 'onion powder'),
('Paprika', 'paprika'),
('Paprika', 'paprika doux'),
('Paprika', 'sweet paprika powder'),
('Paprika', 'sweet paprika'),
('Paprika fumé', 'paprika fume'),
('Paprika fumé', 'smoked paprika'),
('Cumin moulu', 'cumin'),
('Cumin moulu', 'cumin moulu'),
('Cumin moulu', 'ground cumin'),
('Graines de cumin', 'graines de cumin'),
('Graines de cumin', 'cumin seeds'),
('Graines de fenouil', 'graines de fenouil'),
('Graines de fenouil', 'fennel seeds'),
('Coriandre moulue', 'coriandre moulue'),
('Coriandre moulue', 'ground coriander'),
('Graines de coriandre', 'graines de coriandre'),
('Graines de coriandre', 'coriander seeds'),
('Curcuma', 'curcuma'),
('Curcuma', 'turmeric'),
('Garam masala', 'garam masala'),
('Garam masala', 'garam massala'),
('Cari', 'cari'),
('Cari', 'poudre de cari'),
('Cari', 'curry powder'),
('Cannelle', 'cannelle'),
('Cannelle', 'cinnamon'),
('Muscade', 'muscade'),
('Muscade', 'nutmeg'),
('Piment de la Jamaïque', 'piment de la jamaique'),
('Piment de la Jamaïque', 'allspice'),
('Piment de Cayenne', 'piment de cayenne'),
('Piment de Cayenne', 'cayenne'),
('Piment de Cayenne', 'poivre de cayenne'),
('Piment gochugaru', 'gochugaru'),
('Piment gochugaru', 'piment gochugaru'),
('Piment gochugaru', 'flocons de piment gochugaru'),
('Piment gochugaru', 'gochugaru flakes'),
('Piment gochugaru', 'gochugaru chili flakes'),
('Flocons de piment fort', 'flocons de piment'),
('Flocons de piment fort', 'flocons de piment fort'),
('Flocons de piment fort', 'chili flakes'),
('Flocons de piment fort', 'dried chilli flakes'),
('Flocons de piment fort', 'red pepper flakes'),
('Flocons de piment fort', 'piment rouge broye'),
('Flocons de piment fort', 'crushed red pepper'),
('Flocons de piment fort', 'red chili flakes'),
('Flocons de piment fort', 'red chilli flakes'),
('Flocons de piment fort', 'flocons de chili'),
('Flocons de piment fort', 'chilli flakes'),
('Assaisonnement au chili', 'chili powder'),
('Assaisonnement au chili', 'assaisonnement au chili'),
('Assaisonnement au chili', 'poudre de chili'),
('Assaisonnement au chili', 'chilli powder'),
('Moutarde en poudre', 'moutarde en poudre'),
('Moutarde en poudre', 'mustard powder'),
('Feuilles de laurier', 'laurier'),
('Feuilles de laurier', 'feuille de laurier'),
('Feuilles de laurier', 'bay'),
('Feuilles de laurier', 'bay leaf'),
('Feuilles de laurier', 'bay leaves'),
('Thym séché', 'thym'),
('Thym séché', 'thym seche'),
('Thym séché', 'dried thyme'),
('Thym séché', 'thyme'),
('Origan séché', 'origan'),
('Origan séché', 'dried oregano'),
('Origan séché', 'oregano'),
('Basilic séché', 'basilic seche'),
('Basilic séché', 'dried basil'),
('Persil séché', 'persil seche'),
('Persil séché', 'dried parsley'),
('Romarin séché', 'romarin'),
('Romarin séché', 'dried rosemary'),
('Romarin séché', 'romarin seche'),
('Fines herbes italiennes', 'mixed herb'),
('Fines herbes italiennes', 'mixed herbs'),
('Fines herbes italiennes', 'fines herbes'),
('Fines herbes italiennes', 'herbes italiennes'),
('Fines herbes italiennes', 'italian seasoning'),
('Arachides rôties', 'arachides'),
('Arachides rôties', 'peanuts'),
('Arachides rôties', 'roasted peanuts'),
('Amandes', 'amandes'),
('Amandes', 'almonds'),
('Amandes', 'unsalted roasted almonds'),
('Noix de Grenoble', 'noix de grenoble'),
('Noix de Grenoble', 'walnuts'),
('Noix de macadamia', 'noix de macadamia'),
('Noix de macadamia', 'macadamia nuts'),
('Graines de citrouille', 'graines de citrouille'),
('Graines de citrouille', 'pumpkin seeds'),
('Graines de citrouille', 'roasted pumpkin seeds'),
('Graines de citrouille', 'graines de courge'),
('Graines de citrouille', 'pepitas'),
('Graines de sésame grillées', 'graines de sesame'),
('Graines de sésame grillées', 'sesame seeds'),
('Graines de sésame grillées', 'toasted sesame seeds'),
('Graines de sésame grillées', 'white sesame seeds'),
('Croustilles de maïs', 'chips de mais'),
('Croustilles de maïs', 'tortilla chips'),
('Croustilles de maïs', 'nachos'),
('Croustilles de maïs', 'croustilles de mais'),
('Croustilles de maïs', 'croustilles de tortilla'),
('Édamames', 'edamame'),
('Édamames', 'edamames'),
('Édamames', 'frozen edamame in shell'),
('Petits pois surgelés', 'pois surgeles'),
('Petits pois surgelés', 'petits pois'),
('Petits pois surgelés', 'peas'),
('Maïs en grains', 'mais en grains'),
('Maïs en grains', 'corn kernels'),
('Maïs en grains', 'frozen corn'),
('Maïs en grains', 'mais surgele'),
('Maïs en grains', 'mais'),
('Vin blanc', 'vin blanc'),
('Vin blanc', 'white wine'),
('Vin blanc', 'dry white wine'),
('Poireau', 'poireau'),
('Poireau', 'poireaux'),
('Poireau', 'leek'),
('Poireau', 'leeks'),
('Champignons blancs', 'champignons'),
('Champignons blancs', 'champignons blancs'),
('Champignons blancs', 'champignons de paris'),
('Champignons blancs', 'mushrooms'),
('Champignons blancs', 'button mushrooms'),
('Champignons shiitakes', 'shiitake'),
('Champignons shiitakes', 'shiitakes'),
('Champignons shiitakes', 'champignons shiitakes'),
('Champignons shiitakes', 'champignons shiitake'),
('Chou rouge', 'chou rouge'),
('Chou rouge', 'red cabbage'),
('Chou rouge', 'shredded red cabbage'),
('Radis', 'radis'),
('Radis', 'radish'),
('Radis', 'radishes'),
('Laitue romaine', 'laitue romaine'),
('Laitue romaine', 'romaine'),
('Laitue romaine', 'romaine lettuce'),
('Laitue romaine', 'shredded romaine lettuce'),
('Mesclun', 'mesclun'),
('Mesclun', 'laitue'),
('Mesclun', 'mixed leaf lettuce'),
('Mesclun', 'mixed greens'),
('Mesclun', 'salad greens'),
('Grenade', 'grenade'),
('Grenade', 'graines de grenade'),
('Grenade', 'pomegranate'),
('Grenade', 'pomegranate seeds'),
('Pêches', 'peche'),
('Pêches', 'peches'),
('Pêches', 'peach'),
('Pêches', 'peaches'),
('Fines herbes fraîches (au choix)', 'herbes fraiches'),
('Fines herbes fraîches (au choix)', 'fines herbes fraiches'),
('Fines herbes fraîches (au choix)', 'fresh herbs'),
('Halloumi', 'halloumi'),
('Halloumi', 'fromage halloumi'),
('Halloumi', 'fromage a griller'),
('Halloumi', 'grilling cheese'),
('Mozzarella fraîche', 'mozzarella fraiche'),
('Mozzarella fraîche', 'boule de mozzarella'),
('Mozzarella fraîche', 'fresh mozzarella'),
('Mozzarella fraîche', 'burrata'),
('Fromage de chèvre', 'fromage de chevre'),
('Fromage de chèvre', 'chevre'),
('Fromage de chèvre', 'goat cheese'),
('Fromage de chèvre', 'soft goat cheese'),
('Yogourt de soya', 'yogourt de soya'),
('Yogourt de soya', 'soy yogurt'),
('Yogourt de soya', 'unsweetened soy yogurt'),
('Crème végétale à cuisson (Belsoy)', 'creme de soya'),
('Crème végétale à cuisson (Belsoy)', 'belsoy'),
('Crème végétale à cuisson (Belsoy)', 'creme vegetale'),
('Crème végétale à cuisson (Belsoy)', 'creme vegetale a cuisson'),
('Crème végétale à cuisson (Belsoy)', 'plant based cream'),
('Houmous', 'houmous'),
('Houmous', 'hummus'),
('Houmous', 'houmous maison'),
('Pesto', 'pesto'),
('Pesto', 'pesto vegetalien'),
('Pesto', 'vegan pesto'),
('Pains naan', 'naan'),
('Pains naan', 'naans'),
('Pains naan', 'pain naan'),
('Pains naan', 'pains naan'),
('Pains naan', 'pains naans'),
('Pains plats (pita)', 'pain plat'),
('Pains plats (pita)', 'pains plats'),
('Pains plats (pita)', 'flatbread'),
('Pains plats (pita)', 'flatbreads'),
('Pains plats (pita)', 'pita'),
('Pains plats (pita)', 'pitas'),
('Pains plats (pita)', 'pain pita'),
('Pain de campagne (levain)', 'pain de campagne'),
('Pain de campagne (levain)', 'pain au levain'),
('Pain de campagne (levain)', 'sourdough'),
('Pain de campagne (levain)', 'sourdough bread'),
('Pâtes courtes', 'pates'),
('Pâtes courtes', 'pates courtes'),
('Pâtes courtes', 'conchiglie'),
('Pâtes courtes', 'conchiglie rigate'),
('Pâtes courtes', 'penne'),
('Pâtes courtes', 'fusilli'),
('Pâtes courtes', 'rotini'),
('Pâtes courtes', 'short pasta'),
('Pâtes courtes', 'pasta'),
('Nouilles asiatiques (soba, orientales)', 'nouilles'),
('Nouilles asiatiques (soba, orientales)', 'nouilles orientales'),
('Nouilles asiatiques (soba, orientales)', 'soba'),
('Nouilles asiatiques (soba, orientales)', 'nouilles soba'),
('Nouilles asiatiques (soba, orientales)', 'knife pare noodles'),
('Nouilles asiatiques (soba, orientales)', 'knife cut noodles'),
('Nouilles asiatiques (soba, orientales)', 'noodles'),
('Nouilles asiatiques (soba, orientales)', 'egg noodles'),
('Nouilles asiatiques (soba, orientales)', 'nouilles aux oeufs'),
('Purée de citrouille', 'puree de citrouille'),
('Purée de citrouille', 'pumpkin puree'),
('Maïs en crème (conserve)', 'mais en creme'),
('Maïs en crème (conserve)', 'conserve mais en creme'),
('Maïs en crème (conserve)', 'creamed corn'),
('Bouillon de poulet', 'bouillon de poulet'),
('Bouillon de poulet', 'chicken broth'),
('Bouillon de poulet', 'chicken stock'),
('Olives vertes', 'olives vertes'),
('Olives vertes', 'green olives'),
('Olives vertes', 'saumure d olives'),
('Thon en conserve', 'thon'),
('Thon en conserve', 'tuna'),
('Thon en conserve', 'safe catch wild elite tuna'),
('Thon en conserve', 'canned tuna'),
('Chipotle en sauce adobo', 'chipotle'),
('Chipotle en sauce adobo', 'chipotles'),
('Chipotle en sauce adobo', 'chipotle adobo sauce'),
('Chipotle en sauce adobo', 'chipotle en sauce adobo'),
('Chipotle en sauce adobo', 'adobo'),
('Sauce hoisin', 'sauce hoisin'),
('Sauce hoisin', 'hoisin'),
('Sauce hoisin', 'hoisin sauce'),
('Pâte de cari rouge', 'pate de cari rouge'),
('Pâte de cari rouge', 'pate de cari'),
('Pâte de cari rouge', 'red curry paste'),
('Pâte de cari rouge', 'curry paste'),
('Pâte de cari rouge', 'pate de curry'),
('Nouilles de riz', 'nouilles de riz'),
('Nouilles de riz', 'rice noodles'),
('Nouilles de riz', 'vermicelles de riz'),
('Nouilles de riz', 'rice vermicelli'),
('Nouilles de riz', 'pates de riz'),
('Gochujang', 'gochujang'),
('Gochujang', 'pate de piment coreenne'),
('Sauce aux huîtres végétale (champignons)', 'plantbased oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'plant based oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'vegan oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'vegetarian oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres vegetale'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres vegetarienne'),
('Sauce aux huîtres végétale (champignons)', 'mushroom oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres aux champignons'),
('Sauce aux huîtres', 'sauce aux huitres'),
('Sauce aux huîtres', 'oyster sauce'),
('Sauce de poisson', 'sauce poisson'),
('Sauce de poisson', 'sauce de poisson'),
('Sauce de poisson', 'fish sauce'),
('Vinaigre blanc', 'vinaigre blanc'),
('Vinaigre blanc', 'white vinegar'),
('Graines de moutarde', 'graines de moutarde'),
('Graines de moutarde', 'mustard seeds'),
('Épices à tourtière', 'epices a tourtiere'),
('Sumac', 'sumac'),
('Herbes de Provence', 'herbes de provence'),
('Assaisonnement cajun', 'cajun seasoning'),
('Assaisonnement cajun', 'assaisonnement cajun'),
('Assaisonnement cajun', 'epices cajun'),
('Assaisonnement à tacos', 'burrito seasoning'),
('Assaisonnement à tacos', 'taco seasoning'),
('Assaisonnement à tacos', 'assaisonnement a tacos'),
('Assaisonnement à tacos', 'fajita seasoning'),
('Pistaches', 'pistaches'),
('Pistaches', 'pistachios'),
('Noix de cajou', 'noix de cajou'),
('Noix de cajou', 'cashews'),
('Noix de cajou', 'cashew'),
('Noix de cajou', 'cajou'),
('Noix de pin', 'noix de pin'),
('Noix de pin', 'noix de pins'),
('Noix de pin', 'pine nuts'),
('Graines de tournesol', 'graines de tournesol'),
('Graines de tournesol', 'sunflower seeds'),
('Raisins secs', 'raisins secs'),
('Raisins secs', 'raisins sec'),
('Canneberges séchées', 'canneberges sechees'),
('Canneberges séchées', 'dried cranberries'),
('Canneberges séchées', 'cranberries'),
('Noix mélangées', 'noix au choix'),
('Noix mélangées', 'noix melangees'),
('Noix mélangées', 'mixed nuts'),
('Croustilles de pita', 'chips de pita'),
('Croustilles de pita', 'pita chips'),
('Croustilles de pita', 'croustilles de pita'),
('Eau', 'eau'),
('Eau', 'water'),
('Gingembre moulu', 'gingembre moulu'),
('Gingembre moulu', 'gingembre en poudre'),
('Gingembre moulu', 'ground ginger'),
('Gingembre moulu', 'ginger powder'),
('Riz brun', 'riz brun'),
('Riz brun', 'riz brun a grain long'),
('Riz brun', 'riz complet'),
('Riz brun', 'brown rice'),
('Riz brun', 'long grain brown rice'),
('Huile de truffe', 'huile de truffe'),
('Huile de truffe', 'huile a la truffe'),
('Huile de truffe', 'huile de truffe blanche'),
('Huile de truffe', 'truffle oil'),
('Huile de truffe', 'white truffle oil'),
('Poivron jaune', 'poivron jaune'),
('Poivron jaune', 'poivrons jaunes'),
('Poivron jaune', 'poivron orange'),
('Poivron jaune', 'poivrons oranges'),
('Poivron jaune', 'yellow bell pepper'),
('Poivron jaune', 'yellow bell peppers'),
('Poivron jaune', 'yellow pepper'),
('Poivron jaune', 'yellow peppers'),
('Poivron jaune', 'orange bell pepper'),
('Poivron jaune', 'orange bell peppers'),
('Poivron jaune', 'orange pepper'),
('Vinaigre de vin blanc', 'vinaigre de vin blanc'),
('Vinaigre de vin blanc', 'white wine vinegar'),
('Pâte de cari vert', 'pate de cari vert'),
('Pâte de cari vert', 'pate de curry vert'),
('Pâte de cari vert', 'green curry paste'),
('Pâte de cari vert', 'thai green curry paste'),
('Tortillas de maïs', 'tortillas de mais'),
('Tortillas de maïs', 'tortilla de mais'),
('Tortillas de maïs', 'corn tortillas'),
('Tortillas de maïs', 'corn tortilla'),
('Farine de pois chiches', 'farine de pois chiches'),
('Farine de pois chiches', 'farine de pois chiche'),
('Farine de pois chiches', 'chickpea flour'),
('Farine de pois chiches', 'gram flour'),
('Farine de pois chiches', 'besan'),
('Farine de maïs', 'farine de mais'),
('Farine de maïs', 'semoule de mais'),
('Farine de maïs', 'cornmeal'),
('Farine de maïs', 'corn meal'),
('Farine de maïs', 'masa harina'),
('Eau de coco', 'eau de coco'),
('Eau de coco', 'coconut water'),
('Feuilles de lime kaffir', 'feuilles de lime kaffir'),
('Feuilles de lime kaffir', 'feuille de lime kaffir'),
('Feuilles de lime kaffir', 'feuilles de lime'),
('Feuilles de lime kaffir', 'feuilles de kaffir'),
('Feuilles de lime kaffir', 'kaffir lime leaves'),
('Feuilles de lime kaffir', 'kaffir lime leaf'),
('Feuilles de lime kaffir', 'makrut lime leaves'),
('Feuilles de lime kaffir', 'makrut lime leaf'),
('Feuilles de lime kaffir', 'lime leaves'),
('Citronnelle', 'citronnelle'),
('Citronnelle', 'tige de citronnelle'),
('Citronnelle', 'tiges de citronnelle'),
('Citronnelle', 'lemongrass'),
('Citronnelle', 'lemon grass'),
('Citronnelle', 'lemongrass stalk'),
('Citronnelle', 'lemongrass stalks'),
('Mélasse de grenade', 'melasse de grenade'),
('Mélasse de grenade', 'pomegranate molasses'),
('Pois mange-tout', 'pois mange tout'),
('Pois mange-tout', 'pois mangetout'),
('Pois mange-tout', 'pois sucres'),
('Pois mange-tout', 'pois sugar snap'),
('Pois mange-tout', 'snow peas'),
('Pois mange-tout', 'snap peas'),
('Pois mange-tout', 'sugar snap peas'),
('Yogourt végétal', 'yogourt vegetal'),
('Yogourt végétal', 'yogourt vegetalien'),
('Yogourt végétal', 'yogourt vegane'),
('Yogourt végétal', 'yogourt de coco'),
('Yogourt végétal', 'yogourt a la noix de coco'),
('Yogourt végétal', 'coconut yogurt'),
('Yogourt végétal', 'vegan yogurt'),
('Yogourt végétal', 'plant based yogurt'),
('Yogourt végétal', 'dairy free yogurt'),
('Sauce de poisson végétalienne', 'sauce de poisson vegetalienne'),
('Sauce de poisson végétalienne', 'sauce de poisson vegane'),
('Sauce de poisson végétalienne', 'sauce de poisson vegetarienne'),
('Sauce de poisson végétalienne', 'sauce poisson vegetalienne'),
('Sauce de poisson végétalienne', 'vegan fish sauce'),
('Sauce de poisson végétalienne', 'vegetarian fish sauce'),
('Chipotle en poudre', 'chipotle en poudre'),
('Chipotle en poudre', 'piment chipotle moulu'),
('Chipotle en poudre', 'chipotle moulu'),
('Chipotle en poudre', 'chipotle powder'),
('Chipotle en poudre', 'chipotle chili powder'),
('Chipotle en poudre', 'ground chipotle'),
('Crème de champignons (conserve)', 'creme de champignons'),
('Crème de champignons (conserve)', 'soupe creme de champignons'),
('Crème de champignons (conserve)', 'cream of mushroom soup'),
('Crème de champignons (conserve)', 'cream of mushroom'),
('Crème de champignons (conserve)', 'condensed cream of mushroom soup'),
('Galettes de riz', 'galettes de riz'),
('Galettes de riz', 'galette de riz'),
('Galettes de riz', 'feuilles de riz'),
('Galettes de riz', 'feuille de riz'),
('Galettes de riz', 'papier de riz'),
('Galettes de riz', 'rice paper'),
('Galettes de riz', 'rice paper wrappers'),
('Galettes de riz', 'rice paper sheets'),
('Galettes de riz', 'spring roll wrappers'),
('Base de bouillon (pâte)', 'base de bouillon'),
('Base de bouillon (pâte)', 'base de bouillon de legumes'),
('Base de bouillon (pâte)', 'pate de bouillon'),
('Base de bouillon (pâte)', 'concentre de bouillon'),
('Base de bouillon (pâte)', 'concentre de bouillon de legumes'),
('Base de bouillon (pâte)', 'bouillon paste'),
('Base de bouillon (pâte)', 'vegetable bouillon paste'),
('Base de bouillon (pâte)', 'better than bouillon'),
('Base de bouillon (pâte)', 'vegetable bouillon base'),
('Romarin frais', 'romarin frais'),
('Romarin frais', 'branche de romarin'),
('Romarin frais', 'branches de romarin'),
('Romarin frais', 'brin de romarin'),
('Romarin frais', 'brins de romarin'),
('Romarin frais', 'fresh rosemary'),
('Romarin frais', 'rosemary sprig'),
('Romarin frais', 'rosemary sprigs'),
('Romarin frais', 'sprigs of rosemary'),
('Sauge séchée', 'sauge sechee'),
('Sauge séchée', 'sauge moulue'),
('Sauge séchée', 'dried sage'),
('Sauge séchée', 'ground sage'),
('Sauge séchée', 'rubbed sage'),
('Menthe séchée', 'menthe sechee'),
('Menthe séchée', 'dried mint'),
('Vinaigre balsamique blanc', 'vinaigre balsamique blanc'),
('Vinaigre balsamique blanc', 'white balsamic vinegar'),
('Vinaigre balsamique blanc', 'balsamique blanc'),
('Piment doux', 'piment doux'),
('Piment doux', 'piments doux'),
('Piment doux', 'piment chili doux'),
('Piment doux', 'piments chili doux'),
('Piment doux', 'mild chili'),
('Piment doux', 'mild chili pepper'),
('Piment doux', 'mild chilies')
)
delete from ingredient_aliases a using ingredients i where a.ingredient_id = i.id and a.household_id is null and i.household_id is null and not exists (select 1 from c where c.name = i.name and c.alias = a.alias);
with c(name, alias) as (values
('Ail', 'ail'),
('Ail', 'garlic'),
('Ail', 'garlic cloves'),
('Ail', 'ail hache'),
('Ail', 'ail entieres'),
('Ail', 'gousse d ail'),
('Ail', 'gousses d ail'),
('Ail', 'tete d ail'),
('Ail', 'tetes d ail'),
('Oignon jaune', 'oignon'),
('Oignon jaune', 'oignons'),
('Oignon jaune', 'oignon jaune'),
('Oignon jaune', 'oignons jaunes'),
('Oignon jaune', 'onion'),
('Oignon jaune', 'onions'),
('Oignon jaune', 'yellow onion'),
('Oignon rouge', 'oignon rouge'),
('Oignon rouge', 'oignons rouges'),
('Oignon rouge', 'red onion'),
('Oignon rouge', 'red onions'),
('Oignon vert', 'oignon vert'),
('Oignon vert', 'oignons verts'),
('Oignon vert', 'green onion'),
('Oignon vert', 'green onions'),
('Oignon vert', 'green oignons'),
('Oignon vert', 'spring onion'),
('Oignon vert', 'spring onions'),
('Oignon vert', 'scallion'),
('Oignon vert', 'scallions'),
('Oignon vert', 'echalote verte'),
('Échalote française', 'echalote francaise'),
('Échalote française', 'echalotes francaises'),
('Échalote française', 'echalote'),
('Échalote française', 'shallot'),
('Échalote française', 'shallots'),
('Gingembre', 'gingembre'),
('Gingembre', 'gingembre frais'),
('Gingembre', 'ginger'),
('Gingembre', 'ginger root'),
('Céleri', 'celeri'),
('Céleri', 'celery'),
('Carotte', 'carotte'),
('Carotte', 'carottes'),
('Carotte', 'carrot'),
('Carotte', 'carrots'),
('Aubergine', 'aubergine'),
('Aubergine', 'aubergines'),
('Aubergine', 'eggplant'),
('Courgette', 'courgette'),
('Courgette', 'courgettes'),
('Courgette', 'zucchini'),
('Courge musquée (butternut)', 'courge musquee'),
('Courge musquée (butternut)', 'courge butternut'),
('Courge musquée (butternut)', 'butternut squash'),
('Courge musquée (butternut)', 'butternut'),
('Chou-fleur', 'chou fleur'),
('Chou-fleur', 'cauliflower'),
('Brocoli', 'brocoli'),
('Brocoli', 'broccoli'),
('Brocoli', 'couronne de brocoli'),
('Brocoli', 'couronnes de brocoli'),
('Chou de Savoie', 'chou de savoie'),
('Chou de Savoie', 'savoy cabbage'),
('Chou frisé (kale)', 'kale'),
('Chou frisé (kale)', 'chou frise'),
('Épinards', 'epinards'),
('Épinards', 'bebes epinards'),
('Épinards', 'spinach'),
('Épinards', 'baby spinach'),
('Roquette', 'roquette'),
('Roquette', 'arugula'),
('Laitue iceberg', 'laitue iceberg'),
('Laitue iceberg', 'iceberg lettuce'),
('Bok choy', 'bok choy'),
('Bok choy', 'baby bok choy'),
('Bok choy', 'pak choi'),
('Tomate', 'tomate'),
('Tomate', 'tomates'),
('Tomate', 'tomato'),
('Tomate', 'tomatoes'),
('Tomates cerises', 'tomates cerises'),
('Tomates cerises', 'cherry tomatoes'),
('Tomates cerises', 'grape tomatoes'),
('Concombre', 'concombre'),
('Concombre', 'concombres'),
('Concombre', 'cucumber'),
('Concombre', 'cucumbers'),
('Poivron rouge', 'poivron'),
('Poivron rouge', 'poivrons'),
('Poivron rouge', 'poivron rouge'),
('Poivron rouge', 'poivrons rouges'),
('Poivron rouge', 'red bell pepper'),
('Poivron rouge', 'bell pepper'),
('Poivron rouge', 'red pepper'),
('Poivron rouge', 'red peppers'),
('Poivron rouge', 'red bell peppers'),
('Poivron vert', 'poivron vert'),
('Poivron vert', 'poivrons verts'),
('Poivron vert', 'green bell pepper'),
('Poivron vert', 'green pepper'),
('Poivron vert', 'green bell peppers'),
('Poivron vert', 'green peppers'),
('Piment jalapeño', 'piment jalapeno'),
('Piment jalapeño', 'jalapeno'),
('Piment fort frais', 'long green chili pepper'),
('Piment fort frais', 'green chili'),
('Piment fort frais', 'piment vert'),
('Piment fort frais', 'serrano pepper'),
('Piment fort frais', 'piment serrano'),
('Piment fort frais', 'red chilli'),
('Piment fort frais', 'red chili'),
('Piment fort frais', 'piment chili rouge'),
('Piment fort frais', 'piment rouge'),
('Piment fort frais', 'piments chili'),
('Piment fort frais', 'piment chili'),
('Piment fort frais', 'chilli'),
('Piment fort frais', 'chili pepper'),
('Piment fort frais', 'scotch bonnet'),
('Piment fort frais', 'scotch bonnet pepper'),
('Piment fort frais', 'habanero'),
('Piment fort frais', 'piment habanero'),
('Patate douce', 'patate douce'),
('Patate douce', 'patates douces'),
('Patate douce', 'sweet potato'),
('Patate douce', 'sweet potatoes'),
('Pomme de terre', 'pomme de terre'),
('Pomme de terre', 'pommes de terre'),
('Pomme de terre', 'potato'),
('Pomme de terre', 'potatoes'),
('Pomme', 'pomme'),
('Pomme', 'pommes'),
('Pomme', 'apple'),
('Pomme', 'apples'),
('Citron', 'citron'),
('Citron', 'citrons'),
('Citron', 'lemon'),
('Citron', 'lemons'),
('Citron', 'jus de citron'),
('Citron', 'lemon juice'),
('Lime', 'lime'),
('Lime', 'limes'),
('Lime', 'jus de lime'),
('Lime', 'lime juice'),
('Lime', 'citron vert'),
('Avocat', 'avocat'),
('Avocat', 'avocats'),
('Avocat', 'avocado'),
('Avocat', 'avocados'),
('Avocat', 'guacamole'),
('Avocat', 'lazy guacamole'),
('Champignons pleurotes', 'champignons pleurotes'),
('Champignons pleurotes', 'pleurotes'),
('Champignons pleurotes', 'oyster mushrooms'),
('Champignons enoki', 'champignons enokis'),
('Champignons enoki', 'champignons enoki'),
('Champignons enoki', 'enoki'),
('Champignons enoki', 'enoki mushrooms'),
('Fèves germées', 'feves germees'),
('Fèves germées', 'bean sprouts'),
('Coriandre fraîche', 'coriandre'),
('Coriandre fraîche', 'coriandre fraiche'),
('Coriandre fraîche', 'feuilles de coriandre'),
('Coriandre fraîche', 'cilantro'),
('Coriandre fraîche', 'fresh cilantro'),
('Coriandre fraîche', 'fresh coriander'),
('Persil frais', 'persil'),
('Persil frais', 'persil italien'),
('Persil frais', 'persil plat'),
('Persil frais', 'parsley'),
('Persil frais', 'fresh parsley'),
('Basilic frais', 'basilic'),
('Basilic frais', 'feuilles de basilic'),
('Basilic frais', 'basil'),
('Basilic frais', 'fresh basil'),
('Basilic frais', 'fresh basil leaves'),
('Menthe fraîche', 'menthe'),
('Menthe fraîche', 'feuilles de menthe'),
('Menthe fraîche', 'fresh mint'),
('Menthe fraîche', 'fresh mint leaves'),
('Menthe fraîche', 'menthe fraiche'),
('Menthe fraîche', 'mint leaves'),
('Aneth frais', 'aneth'),
('Aneth frais', 'dill'),
('Ciboulette', 'ciboulette'),
('Ciboulette', 'chives'),
('Sauge fraîche', 'sauge'),
('Sauge fraîche', 'feuilles de sauge'),
('Sauge fraîche', 'sage'),
('Sauge fraîche', 'sauge fraiche'),
('Sauge fraîche', 'fresh sage'),
('Sauge fraîche', 'fresh sage leaves'),
('Sauge fraîche', 'sage leaves'),
('Maïs en épi', 'epi de mais'),
('Maïs en épi', 'epis de mais'),
('Maïs en épi', 'mais en epi'),
('Maïs en épi', 'corn on the cob'),
('Maïs en épi', 'ears of corn'),
('Légumes d''accompagnement (au choix)', 'legumes pour accompagner le tofu'),
('Légumes d''accompagnement (au choix)', 'legumes pour accompagner'),
('Légumes d''accompagnement (au choix)', 'legumes d accompagnement'),
('Légumes d''accompagnement (au choix)', 'legumes au choix'),
('Thym frais', 'thym frais'),
('Thym frais', 'fresh thyme'),
('Thym frais', 'branches de thym'),
('Thym frais', 'thyme sprigs'),
('Thym frais', 'thyme sprig'),
('Thym frais', 'sprigs of thyme'),
('Thym frais', 'sprigs thyme'),
('Thym frais', 'fresh thyme sprigs'),
('Thym frais', 'brins de thym'),
('Thym frais', 'branche de thym'),
('Origan frais', 'origan frais'),
('Origan frais', 'fresh oregano'),
('Pousses de luzerne', 'luzerne'),
('Pousses de luzerne', 'alfalfa sprouts'),
('Tofu ferme', 'tofu'),
('Tofu ferme', 'tofu ferme'),
('Tofu ferme', 'firm tofu'),
('Tofu ferme', 'sofritas'),
('Tofu extra-ferme', 'tofu extra ferme'),
('Tofu extra-ferme', 'extra firm tofu'),
('Tofu soyeux', 'tofu soyeux'),
('Tofu soyeux', 'silken tofu'),
('Tempeh', 'tempeh'),
('Haché végé', 'vegan mince'),
('Haché végé', 'hache vege'),
('Haché végé', 'hache vegetal'),
('Beurre végétal', 'vegan butter'),
('Beurre végétal', 'beurre vegetal'),
('Beurre végétal', 'margarine'),
('Miso blanc', 'miso'),
('Miso blanc', 'white miso paste'),
('Miso blanc', 'miso blanc'),
('Miso blanc', 'pate miso'),
('Nouilles udon', 'udon noodles'),
('Nouilles udon', 'nouilles udon'),
('Nouilles udon', 'udon'),
('Beurre', 'beurre'),
('Beurre', 'beurre non sale'),
('Beurre', 'butter'),
('Beurre', 'unsalted butter'),
('Lait', 'lait'),
('Lait', 'milk'),
('Boisson végétale', 'lait vegetal'),
('Boisson végétale', 'boisson vegetale'),
('Boisson végétale', 'plant milk'),
('Boisson végétale', 'oat milk'),
('Boisson végétale', 'lait d amande'),
('Boisson végétale', 'almond milk'),
('Boisson végétale', 'lait de riz'),
('Boisson végétale', 'rice milk'),
('Boisson végétale', 'lait d avoine'),
('Boisson végétale', 'lait de cajou'),
('Boisson végétale', 'cashew milk'),
('Boisson végétale', 'boisson d avoine'),
('Boisson végétale', 'boisson d amande'),
('Boisson végétale', 'boisson de soya'),
('Boisson végétale', 'lait de soya'),
('Boisson végétale', 'soy milk'),
('Crème sure', 'creme sure'),
('Crème sure', 'sour cream'),
('Crème sure végétalienne', 'creme sure vegetalienne'),
('Crème sure végétalienne', 'vegan sour cream'),
('Yogourt nature', 'yogourt'),
('Yogourt nature', 'yogourt nature'),
('Yogourt nature', 'plain yogurt'),
('Crème à cuisson 15 %', 'creme a cuisson'),
('Crème à cuisson 15 %', 'cooking cream'),
('Feta', 'feta'),
('Feta', 'fromage feta'),
('Feta', 'feta cheese'),
('Parmesan', 'parmesan'),
('Parmesan', 'parmigiano'),
('Parmesan végane', 'vegan parmesan'),
('Parmesan végane', 'parmesan vegane'),
('Parmesan végane', 'vegan parm'),
('Parmesan végane', 'parmesan vegetal'),
('Parmesan végane', 'parmesan vegan'),
('Parmesan végane', 'parmesan vegetalien'),
('Parmesan végane', 'parmesan vegetalienne'),
('Cheddar fort', 'cheddar'),
('Cheddar fort', 'cheddar fort'),
('Fromage végane râpé', 'grated vegan cheese'),
('Fromage végane râpé', 'vegan cheese'),
('Fromage végane râpé', 'fromage vegetalien'),
('Fromage végane râpé', 'vegan feta'),
('Fromage végane râpé', 'vegan cheddar'),
('Fromage végane râpé', 'fromage vegane'),
('Fromage végane râpé', 'feta vegetalienne'),
('Fromage végane râpé', 'feta vegane'),
('Fromage végane râpé', 'cheddar vegetalien'),
('Fromage végane râpé', 'cheddar vegane'),
('Fromage végane râpé', 'fromage vegetal'),
('Fromage végane râpé', 'vegan mozzarella'),
('Fromage végane râpé', 'mozzarella vegetalienne'),
('Œufs', 'oeuf'),
('Œufs', 'oeufs'),
('Œufs', 'egg'),
('Œufs', 'eggs'),
('Hauts de cuisse de poulet désossés', 'hauts de cuisse de poulet'),
('Hauts de cuisse de poulet désossés', 'chicken thighs'),
('Tortillas de blé', 'tortilla'),
('Tortillas de blé', 'tortillas'),
('Tortillas de blé', 'tortillas de ble'),
('Tortillas de blé', 'tortilla de ble'),
('Tortillas de blé', 'flour tortillas'),
('Tortillas de blé', 'soft flour tortillas'),
('Tortillas de blé', 'small soft flour tortillas'),
('Tortillas de blé', 'tortillas de farine'),
('Pâte à tarte', 'pate a tarte'),
('Pâte à tarte', 'pates a tarte'),
('Pâte à tarte', 'abaisse'),
('Pâte à tarte', 'abaisses'),
('Pâte à tarte', 'pie crust'),
('Pâte à tarte', 'pie dough'),
('Croûtons', 'croutons'),
('Quinoa', 'quinoa'),
('Orge perlé', 'orge'),
('Orge perlé', 'orge perle'),
('Orge perlé', 'barley'),
('Orge perlé', 'pearl barley'),
('Riz à risotto (arborio)', 'riz a risotto'),
('Riz à risotto (arborio)', 'arborio'),
('Riz à sushi', 'riz a sushi'),
('Riz à sushi', 'sushi rice'),
('Riz blanc', 'riz'),
('Riz blanc', 'riz blanc'),
('Riz blanc', 'white rice'),
('Riz blanc', 'rice'),
('Riz blanc', 'feculents'),
('Riz blanc', 'feculents au choix'),
('Riz blanc', 'riz basmati'),
('Riz blanc', 'basmati rice'),
('Riz blanc', 'riz jasmin'),
('Riz sauvage', 'riz sauvage'),
('Riz sauvage', 'wild rice'),
('Couscous perlé', 'couscous perle'),
('Couscous perlé', 'pearl couscous'),
('Macaronis', 'macaroni'),
('Macaronis', 'macaronis'),
('Pâtes à lasagne', 'lasagnes'),
('Pâtes à lasagne', 'pates a lasagne'),
('Pâtes à lasagne', 'lasagna sheets'),
('Pâtes à lasagne', 'dried lasagna sheets'),
('Nouilles ramen', 'nouilles ramen'),
('Nouilles ramen', 'ramen noodles'),
('Nouilles ramen', 'nouilles instantanees'),
('Lentilles brunes ou vertes (sèches)', 'lentilles brunes seches'),
('Lentilles brunes ou vertes (sèches)', 'lentilles vertes seches'),
('Lentilles brunes ou vertes (sèches)', 'lentilles seches'),
('Lentilles brunes ou vertes (sèches)', 'dried brown lentils'),
('Lentilles brunes ou vertes (sèches)', 'dried green lentils'),
('Lentilles brunes ou vertes (sèches)', 'dried lentils'),
('Lentilles brunes ou vertes (sèches)', 'lentilles vertes'),
('Lentilles brunes ou vertes (sèches)', 'lentilles du puy'),
('Lentilles brunes ou vertes (sèches)', 'green lentils'),
('Lentilles brunes ou vertes (sèches)', 'french lentils'),
('Lentilles corail', 'lentilles corail'),
('Lentilles corail', 'red lentils'),
('Lentilles corail', 'red split lentils'),
('Lentilles corail', 'lentilles rouges'),
('Chapelure panko', 'chapelure panko'),
('Chapelure panko', 'panko'),
('Chapelure', 'chapelure'),
('Chapelure', 'chapelure italienne'),
('Chapelure', 'breadcrumbs'),
('Pois chiches (conserve)', 'pois chiche'),
('Pois chiches (conserve)', 'pois chiches'),
('Pois chiches (conserve)', 'chickpeas'),
('Pois chiches (conserve)', 'cooked chickpeas'),
('Haricots noirs (conserve)', 'haricots noirs'),
('Haricots noirs (conserve)', 'black beans'),
('Haricots blancs (conserve)', 'haricot blanc'),
('Haricots blancs (conserve)', 'haricots blancs'),
('Haricots blancs (conserve)', 'white beans'),
('Haricots blancs (conserve)', 'white kidney beans'),
('Haricots blancs (conserve)', 'cannellini'),
('Haricots blancs (conserve)', 'cannellini beans'),
('Haricots blancs (conserve)', 'haricots cannellini'),
('Haricots rouges (conserve)', 'haricots rouges'),
('Haricots rouges (conserve)', 'kidney beans'),
('Haricots rouges (conserve)', 'cooked kidney beans'),
('Haricots pinto (conserve)', 'haricots pinto'),
('Haricots pinto (conserve)', 'pinto beans'),
('Haricots pinto (conserve)', 'cooked pinto beans'),
('Lentilles brunes (conserve)', 'lentilles brunes'),
('Lentilles brunes (conserve)', 'cooked brown lentils'),
('Lentilles brunes (conserve)', 'brown lentils'),
('Lentilles brunes (conserve)', 'lentils'),
('Lentilles brunes (conserve)', 'canned lentils'),
('Lentilles brunes (conserve)', 'lentilles en conserve'),
('Lentilles brunes (conserve)', 'lentilles cuites'),
('Lentilles brunes (conserve)', 'cooked lentils'),
('Lentilles brunes (conserve)', 'lentilles vertes en conserve'),
('Tomates en dés (conserve)', 'tomates en des'),
('Tomates en dés (conserve)', 'tomates concassees'),
('Tomates en dés (conserve)', 'chopped tomatoes'),
('Tomates en dés (conserve)', 'diced tomatoes'),
('Sauce tomate (conserve)', 'sauce tomate'),
('Sauce tomate (conserve)', 'tomato sauce'),
('Sauce tomate (conserve)', 'passata'),
('Sauce tomate (conserve)', 'coulis de tomates'),
('Sauce tomate (conserve)', 'tomates broyees'),
('Sauce tomate (conserve)', 'crushed tomatoes'),
('Tomates entières (conserve)', 'whole peeled tomatoes'),
('Tomates entières (conserve)', 'peeled tomatoes'),
('Tomates entières (conserve)', 'tomates entieres'),
('Tomates entières (conserve)', 'tomates entieres pelees'),
('Tomates entières (conserve)', 'tomates pelees'),
('Tomates entières (conserve)', 'tomates en conserve'),
('Tomates entières (conserve)', 'canned tomatoes'),
('Tomates entières (conserve)', 'tinned tomatoes'),
('Poivrons rouges rôtis (pot)', 'poivrons rouges rotis'),
('Poivrons rouges rôtis (pot)', 'poivron rouge roti'),
('Poivrons rouges rôtis (pot)', 'poivrons rotis'),
('Poivrons rouges rôtis (pot)', 'roasted red peppers'),
('Poivrons rouges rôtis (pot)', 'roasted red pepper'),
('Pâte de tomate', 'pate de tomate'),
('Pâte de tomate', 'pate de tomates'),
('Pâte de tomate', 'tomato paste'),
('Pâte de tomate', 'tomato puree'),
('Tomates séchées', 'tomates sechees'),
('Tomates séchées', 'sun dried tomatoes'),
('Tomates séchées', 'sundried tomatoes'),
('Tomates séchées', 'sundried tomato'),
('Lait de coco', 'lait de coco'),
('Lait de coco', 'coconut milk'),
('Lait de coco', 'lait de coconut'),
('Crème de coco', 'creme de coco'),
('Crème de coco', 'coconut cream'),
('Bouillon de légumes', 'bouillon de legumes'),
('Bouillon de légumes', 'vegetable stock'),
('Bouillon de légumes', 'vegetable broth'),
('Bouillon de légumes', 'vegetable stock cube'),
('Bouillon de légumes', 'cube de bouillon'),
('Bouillon aux champignons', 'bouillon aux champignons'),
('Bouillon aux champignons', 'mushroom broth'),
('Olives noires', 'olives noires'),
('Olives noires', 'black olives'),
('Câpres', 'capres'),
('Câpres', 'capers'),
('Oignons marinés', 'oignons marines'),
('Oignons marinés', 'oignon marine'),
('Oignons marinés', 'pickled onions'),
('Oignons marinés', 'pickled red onions'),
('Oignons marinés', 'oignons rouges marines'),
('Cornichons', 'cornichons'),
('Cornichons', 'pickles'),
('Sauce aux canneberges', 'sauce aux canneberges'),
('Sauce aux canneberges', 'cranberry sauce'),
('Champignons séchés', 'champignons seches'),
('Champignons séchés', 'champignons forestiers seches'),
('Champignons séchés', 'dried mushrooms'),
('Pâte de fèves pimentée (doubanjiang)', 'doubanjiang'),
('Feuilles de nori', 'nori'),
('Feuilles de nori', 'nori sheets'),
('Feuilles de nori', 'feuilles de nori'),
('Sambal oelek', 'sambal oelek'),
('Sambal oelek', 'puree de piment'),
('Sambal oelek', 'chili paste'),
('Huile d''olive', 'huile d olive'),
('Huile d''olive', 'olive oil'),
('Huile végétale', 'huile'),
('Huile végétale', 'oil'),
('Huile végétale', 'huile vegetale'),
('Huile végétale', 'vegetable oil'),
('Huile végétale', 'huile de canola'),
('Huile végétale', 'canola oil'),
('Huile de coco', 'huile de coco'),
('Huile de coco', 'coconut oil'),
('Huile d''avocat', 'huile d avocat'),
('Huile d''avocat', 'avocado oil'),
('Huile de sésame grillé', 'huile de sesame'),
('Huile de sésame grillé', 'sesame oil'),
('Huile de sésame grillé', 'toasted sesame oil'),
('Huile pimentée (chili croquant)', 'chili oil'),
('Huile pimentée (chili croquant)', 'chilli oil'),
('Huile pimentée (chili croquant)', 'chili crisp oil'),
('Huile pimentée (chili croquant)', 'chili croquant'),
('Huile pimentée (chili croquant)', 'huile piquante'),
('Huile pimentée (chili croquant)', 'huile pimentee'),
('Huile pimentée (chili croquant)', 'chili crisp'),
('Huile pimentée (chili croquant)', 'huile epicee'),
('Sauce soya', 'sauce soya'),
('Sauce soya', 'sauce soja'),
('Sauce soya', 'soy sauce'),
('Sauce soya', 'light soy sauce'),
('Sauce soya', 'reduced sodium soy sauce'),
('Sauce soya', 'sodium reduced soy sauce'),
('Sauce soya', 'tamari'),
('Sauce soya foncée', 'dark soy sauce'),
('Sauce soya foncée', 'sauce soya foncee'),
('Vinaigre de riz', 'vinaigre de riz'),
('Vinaigre de riz', 'rice vinegar'),
('Vinaigre de riz', 'vinaigre riz'),
('Vinaigre de riz', 'rice wine vinegar'),
('Vinaigre de riz', 'vinaigre de vin de riz'),
('Vinaigre de vin rouge', 'vinaigre de vin'),
('Vinaigre de vin rouge', 'vinaigre de vin rouge'),
('Vinaigre de vin rouge', 'red wine vinegar'),
('Vinaigre balsamique', 'vinaigre balsamique'),
('Vinaigre balsamique', 'balsamic vinegar'),
('Vinaigre de cidre', 'vinaigre de cidre'),
('Vinaigre de cidre', 'apple cider vinegar'),
('Moutarde de Dijon', 'moutarde de dijon'),
('Moutarde de Dijon', 'dijon mustard'),
('Moutarde à l''ancienne', 'moutarde a l ancienne'),
('Moutarde à l''ancienne', 'wholegrain mustard'),
('Mayonnaise', 'mayonnaise'),
('Mayonnaise', 'mayo'),
('Mayonnaise végétalienne (Vegenaise)', 'vegenaise'),
('Mayonnaise végétalienne (Vegenaise)', 'mayonnaise vegetalienne'),
('Mayonnaise végétalienne (Vegenaise)', 'vegan mayo'),
('Mayonnaise végétalienne (Vegenaise)', 'vegan mayonnaise'),
('Harissa', 'harissa'),
('Harissa', 'pate harissa'),
('Harissa', 'pate de harissa'),
('Sauce piquante', 'sauce piquante'),
('Sauce piquante', 'hot sauce'),
('Sauce piquante', 'sriracha'),
('Sauce piri-piri', 'sauce piri piri'),
('Sauce piri-piri', 'piri piri sauce'),
('Sauce barbecue', 'sauce bbq'),
('Sauce barbecue', 'bbq sauce'),
('Sauce barbecue', 'sauce barbecue'),
('Sauce Worcestershire', 'sauce worcestershire'),
('Sauce Worcestershire', 'worcestershire sauce'),
('Sirop d''érable', 'sirop d erable'),
('Sirop d''érable', 'maple syrup'),
('Miel', 'miel'),
('Miel', 'honey'),
('Beurre d''arachide', 'beurre d arachide'),
('Beurre d''arachide', 'peanut butter'),
('Beurre d''amande ou de cajou', 'beurre d amande'),
('Beurre d''amande ou de cajou', 'beurre de cajou'),
('Beurre d''amande ou de cajou', 'beurre de noix de cajou'),
('Beurre d''amande ou de cajou', 'almond butter'),
('Beurre d''amande ou de cajou', 'cashew butter'),
('Tahini', 'tahini'),
('Tahini', 'tahin'),
('Tahini', 'sesame paste'),
('Farine tout usage', 'farine'),
('Farine tout usage', 'farine tout usage'),
('Farine tout usage', 'farine blanche tout usage'),
('Farine tout usage', 'flour'),
('Farine tout usage', 'all purpose flour'),
('Fécule de maïs', 'fecule de mais'),
('Fécule de maïs', 'cornstarch'),
('Fécule de maïs', 'corn starch'),
('Fécule de maïs', 'fecule'),
('Cassonade', 'cassonade'),
('Cassonade', 'brown sugar'),
('Cassonade', 'sucre brun'),
('Cassonade', 'light brown sugar'),
('Cassonade', 'dark brown sugar'),
('Sucre', 'sucre'),
('Sucre', 'sugar'),
('Sucre', 'cane sugar'),
('Sucre', 'sucre de canne'),
('Levure alimentaire', 'levure alimentaire'),
('Levure alimentaire', 'levure nutritionnelle'),
('Levure alimentaire', 'nutritional yeast'),
('Sel', 'sel'),
('Sel', 'salt'),
('Sel', 'sea salt'),
('Sel', 'sel casher'),
('Sel', 'kosher salt'),
('Sel', 'sel et poivre'),
('Poivre noir', 'poivre'),
('Poivre noir', 'poivre noir'),
('Poivre noir', 'poivre du moulin'),
('Poivre noir', 'pepper'),
('Poivre noir', 'black pepper'),
('Poivre noir', 'ground black pepper'),
('Poivre noir', 'cracked black pepper'),
('Poivre noir', 'black pepper corns'),
('Poudre d''ail', 'poudre d ail'),
('Poudre d''ail', 'garlic powder'),
('Poudre d''oignon', 'poudre d oignon'),
('Poudre d''oignon', 'onion powder'),
('Paprika', 'paprika'),
('Paprika', 'paprika doux'),
('Paprika', 'sweet paprika powder'),
('Paprika', 'sweet paprika'),
('Paprika fumé', 'paprika fume'),
('Paprika fumé', 'smoked paprika'),
('Cumin moulu', 'cumin'),
('Cumin moulu', 'cumin moulu'),
('Cumin moulu', 'ground cumin'),
('Graines de cumin', 'graines de cumin'),
('Graines de cumin', 'cumin seeds'),
('Graines de fenouil', 'graines de fenouil'),
('Graines de fenouil', 'fennel seeds'),
('Coriandre moulue', 'coriandre moulue'),
('Coriandre moulue', 'ground coriander'),
('Graines de coriandre', 'graines de coriandre'),
('Graines de coriandre', 'coriander seeds'),
('Curcuma', 'curcuma'),
('Curcuma', 'turmeric'),
('Garam masala', 'garam masala'),
('Garam masala', 'garam massala'),
('Cari', 'cari'),
('Cari', 'poudre de cari'),
('Cari', 'curry powder'),
('Cannelle', 'cannelle'),
('Cannelle', 'cinnamon'),
('Muscade', 'muscade'),
('Muscade', 'nutmeg'),
('Piment de la Jamaïque', 'piment de la jamaique'),
('Piment de la Jamaïque', 'allspice'),
('Piment de Cayenne', 'piment de cayenne'),
('Piment de Cayenne', 'cayenne'),
('Piment de Cayenne', 'poivre de cayenne'),
('Piment gochugaru', 'gochugaru'),
('Piment gochugaru', 'piment gochugaru'),
('Piment gochugaru', 'flocons de piment gochugaru'),
('Piment gochugaru', 'gochugaru flakes'),
('Piment gochugaru', 'gochugaru chili flakes'),
('Flocons de piment fort', 'flocons de piment'),
('Flocons de piment fort', 'flocons de piment fort'),
('Flocons de piment fort', 'chili flakes'),
('Flocons de piment fort', 'dried chilli flakes'),
('Flocons de piment fort', 'red pepper flakes'),
('Flocons de piment fort', 'piment rouge broye'),
('Flocons de piment fort', 'crushed red pepper'),
('Flocons de piment fort', 'red chili flakes'),
('Flocons de piment fort', 'red chilli flakes'),
('Flocons de piment fort', 'flocons de chili'),
('Flocons de piment fort', 'chilli flakes'),
('Assaisonnement au chili', 'chili powder'),
('Assaisonnement au chili', 'assaisonnement au chili'),
('Assaisonnement au chili', 'poudre de chili'),
('Assaisonnement au chili', 'chilli powder'),
('Moutarde en poudre', 'moutarde en poudre'),
('Moutarde en poudre', 'mustard powder'),
('Feuilles de laurier', 'laurier'),
('Feuilles de laurier', 'feuille de laurier'),
('Feuilles de laurier', 'bay'),
('Feuilles de laurier', 'bay leaf'),
('Feuilles de laurier', 'bay leaves'),
('Thym séché', 'thym'),
('Thym séché', 'thym seche'),
('Thym séché', 'dried thyme'),
('Thym séché', 'thyme'),
('Origan séché', 'origan'),
('Origan séché', 'dried oregano'),
('Origan séché', 'oregano'),
('Basilic séché', 'basilic seche'),
('Basilic séché', 'dried basil'),
('Persil séché', 'persil seche'),
('Persil séché', 'dried parsley'),
('Romarin séché', 'romarin'),
('Romarin séché', 'dried rosemary'),
('Romarin séché', 'romarin seche'),
('Fines herbes italiennes', 'mixed herb'),
('Fines herbes italiennes', 'mixed herbs'),
('Fines herbes italiennes', 'fines herbes'),
('Fines herbes italiennes', 'herbes italiennes'),
('Fines herbes italiennes', 'italian seasoning'),
('Arachides rôties', 'arachides'),
('Arachides rôties', 'peanuts'),
('Arachides rôties', 'roasted peanuts'),
('Amandes', 'amandes'),
('Amandes', 'almonds'),
('Amandes', 'unsalted roasted almonds'),
('Noix de Grenoble', 'noix de grenoble'),
('Noix de Grenoble', 'walnuts'),
('Noix de macadamia', 'noix de macadamia'),
('Noix de macadamia', 'macadamia nuts'),
('Graines de citrouille', 'graines de citrouille'),
('Graines de citrouille', 'pumpkin seeds'),
('Graines de citrouille', 'roasted pumpkin seeds'),
('Graines de citrouille', 'graines de courge'),
('Graines de citrouille', 'pepitas'),
('Graines de sésame grillées', 'graines de sesame'),
('Graines de sésame grillées', 'sesame seeds'),
('Graines de sésame grillées', 'toasted sesame seeds'),
('Graines de sésame grillées', 'white sesame seeds'),
('Croustilles de maïs', 'chips de mais'),
('Croustilles de maïs', 'tortilla chips'),
('Croustilles de maïs', 'nachos'),
('Croustilles de maïs', 'croustilles de mais'),
('Croustilles de maïs', 'croustilles de tortilla'),
('Édamames', 'edamame'),
('Édamames', 'edamames'),
('Édamames', 'frozen edamame in shell'),
('Petits pois surgelés', 'pois surgeles'),
('Petits pois surgelés', 'petits pois'),
('Petits pois surgelés', 'peas'),
('Maïs en grains', 'mais en grains'),
('Maïs en grains', 'corn kernels'),
('Maïs en grains', 'frozen corn'),
('Maïs en grains', 'mais surgele'),
('Maïs en grains', 'mais'),
('Vin blanc', 'vin blanc'),
('Vin blanc', 'white wine'),
('Vin blanc', 'dry white wine'),
('Poireau', 'poireau'),
('Poireau', 'poireaux'),
('Poireau', 'leek'),
('Poireau', 'leeks'),
('Champignons blancs', 'champignons'),
('Champignons blancs', 'champignons blancs'),
('Champignons blancs', 'champignons de paris'),
('Champignons blancs', 'mushrooms'),
('Champignons blancs', 'button mushrooms'),
('Champignons shiitakes', 'shiitake'),
('Champignons shiitakes', 'shiitakes'),
('Champignons shiitakes', 'champignons shiitakes'),
('Champignons shiitakes', 'champignons shiitake'),
('Chou rouge', 'chou rouge'),
('Chou rouge', 'red cabbage'),
('Chou rouge', 'shredded red cabbage'),
('Radis', 'radis'),
('Radis', 'radish'),
('Radis', 'radishes'),
('Laitue romaine', 'laitue romaine'),
('Laitue romaine', 'romaine'),
('Laitue romaine', 'romaine lettuce'),
('Laitue romaine', 'shredded romaine lettuce'),
('Mesclun', 'mesclun'),
('Mesclun', 'laitue'),
('Mesclun', 'mixed leaf lettuce'),
('Mesclun', 'mixed greens'),
('Mesclun', 'salad greens'),
('Grenade', 'grenade'),
('Grenade', 'graines de grenade'),
('Grenade', 'pomegranate'),
('Grenade', 'pomegranate seeds'),
('Pêches', 'peche'),
('Pêches', 'peches'),
('Pêches', 'peach'),
('Pêches', 'peaches'),
('Fines herbes fraîches (au choix)', 'herbes fraiches'),
('Fines herbes fraîches (au choix)', 'fines herbes fraiches'),
('Fines herbes fraîches (au choix)', 'fresh herbs'),
('Halloumi', 'halloumi'),
('Halloumi', 'fromage halloumi'),
('Halloumi', 'fromage a griller'),
('Halloumi', 'grilling cheese'),
('Mozzarella fraîche', 'mozzarella fraiche'),
('Mozzarella fraîche', 'boule de mozzarella'),
('Mozzarella fraîche', 'fresh mozzarella'),
('Mozzarella fraîche', 'burrata'),
('Fromage de chèvre', 'fromage de chevre'),
('Fromage de chèvre', 'chevre'),
('Fromage de chèvre', 'goat cheese'),
('Fromage de chèvre', 'soft goat cheese'),
('Yogourt de soya', 'yogourt de soya'),
('Yogourt de soya', 'soy yogurt'),
('Yogourt de soya', 'unsweetened soy yogurt'),
('Crème végétale à cuisson (Belsoy)', 'creme de soya'),
('Crème végétale à cuisson (Belsoy)', 'belsoy'),
('Crème végétale à cuisson (Belsoy)', 'creme vegetale'),
('Crème végétale à cuisson (Belsoy)', 'creme vegetale a cuisson'),
('Crème végétale à cuisson (Belsoy)', 'plant based cream'),
('Houmous', 'houmous'),
('Houmous', 'hummus'),
('Houmous', 'houmous maison'),
('Pesto', 'pesto'),
('Pesto', 'pesto vegetalien'),
('Pesto', 'vegan pesto'),
('Pains naan', 'naan'),
('Pains naan', 'naans'),
('Pains naan', 'pain naan'),
('Pains naan', 'pains naan'),
('Pains naan', 'pains naans'),
('Pains plats (pita)', 'pain plat'),
('Pains plats (pita)', 'pains plats'),
('Pains plats (pita)', 'flatbread'),
('Pains plats (pita)', 'flatbreads'),
('Pains plats (pita)', 'pita'),
('Pains plats (pita)', 'pitas'),
('Pains plats (pita)', 'pain pita'),
('Pain de campagne (levain)', 'pain de campagne'),
('Pain de campagne (levain)', 'pain au levain'),
('Pain de campagne (levain)', 'sourdough'),
('Pain de campagne (levain)', 'sourdough bread'),
('Pâtes courtes', 'pates'),
('Pâtes courtes', 'pates courtes'),
('Pâtes courtes', 'conchiglie'),
('Pâtes courtes', 'conchiglie rigate'),
('Pâtes courtes', 'penne'),
('Pâtes courtes', 'fusilli'),
('Pâtes courtes', 'rotini'),
('Pâtes courtes', 'short pasta'),
('Pâtes courtes', 'pasta'),
('Nouilles asiatiques (soba, orientales)', 'nouilles'),
('Nouilles asiatiques (soba, orientales)', 'nouilles orientales'),
('Nouilles asiatiques (soba, orientales)', 'soba'),
('Nouilles asiatiques (soba, orientales)', 'nouilles soba'),
('Nouilles asiatiques (soba, orientales)', 'knife pare noodles'),
('Nouilles asiatiques (soba, orientales)', 'knife cut noodles'),
('Nouilles asiatiques (soba, orientales)', 'noodles'),
('Nouilles asiatiques (soba, orientales)', 'egg noodles'),
('Nouilles asiatiques (soba, orientales)', 'nouilles aux oeufs'),
('Purée de citrouille', 'puree de citrouille'),
('Purée de citrouille', 'pumpkin puree'),
('Maïs en crème (conserve)', 'mais en creme'),
('Maïs en crème (conserve)', 'conserve mais en creme'),
('Maïs en crème (conserve)', 'creamed corn'),
('Bouillon de poulet', 'bouillon de poulet'),
('Bouillon de poulet', 'chicken broth'),
('Bouillon de poulet', 'chicken stock'),
('Olives vertes', 'olives vertes'),
('Olives vertes', 'green olives'),
('Olives vertes', 'saumure d olives'),
('Thon en conserve', 'thon'),
('Thon en conserve', 'tuna'),
('Thon en conserve', 'safe catch wild elite tuna'),
('Thon en conserve', 'canned tuna'),
('Chipotle en sauce adobo', 'chipotle'),
('Chipotle en sauce adobo', 'chipotles'),
('Chipotle en sauce adobo', 'chipotle adobo sauce'),
('Chipotle en sauce adobo', 'chipotle en sauce adobo'),
('Chipotle en sauce adobo', 'adobo'),
('Sauce hoisin', 'sauce hoisin'),
('Sauce hoisin', 'hoisin'),
('Sauce hoisin', 'hoisin sauce'),
('Pâte de cari rouge', 'pate de cari rouge'),
('Pâte de cari rouge', 'pate de cari'),
('Pâte de cari rouge', 'red curry paste'),
('Pâte de cari rouge', 'curry paste'),
('Pâte de cari rouge', 'pate de curry'),
('Nouilles de riz', 'nouilles de riz'),
('Nouilles de riz', 'rice noodles'),
('Nouilles de riz', 'vermicelles de riz'),
('Nouilles de riz', 'rice vermicelli'),
('Nouilles de riz', 'pates de riz'),
('Gochujang', 'gochujang'),
('Gochujang', 'pate de piment coreenne'),
('Sauce aux huîtres végétale (champignons)', 'plantbased oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'plant based oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'vegan oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'vegetarian oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres vegetale'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres vegetarienne'),
('Sauce aux huîtres végétale (champignons)', 'mushroom oyster sauce'),
('Sauce aux huîtres végétale (champignons)', 'sauce aux huitres aux champignons'),
('Sauce aux huîtres', 'sauce aux huitres'),
('Sauce aux huîtres', 'oyster sauce'),
('Sauce de poisson', 'sauce poisson'),
('Sauce de poisson', 'sauce de poisson'),
('Sauce de poisson', 'fish sauce'),
('Vinaigre blanc', 'vinaigre blanc'),
('Vinaigre blanc', 'white vinegar'),
('Graines de moutarde', 'graines de moutarde'),
('Graines de moutarde', 'mustard seeds'),
('Épices à tourtière', 'epices a tourtiere'),
('Sumac', 'sumac'),
('Herbes de Provence', 'herbes de provence'),
('Assaisonnement cajun', 'cajun seasoning'),
('Assaisonnement cajun', 'assaisonnement cajun'),
('Assaisonnement cajun', 'epices cajun'),
('Assaisonnement à tacos', 'burrito seasoning'),
('Assaisonnement à tacos', 'taco seasoning'),
('Assaisonnement à tacos', 'assaisonnement a tacos'),
('Assaisonnement à tacos', 'fajita seasoning'),
('Pistaches', 'pistaches'),
('Pistaches', 'pistachios'),
('Noix de cajou', 'noix de cajou'),
('Noix de cajou', 'cashews'),
('Noix de cajou', 'cashew'),
('Noix de cajou', 'cajou'),
('Noix de pin', 'noix de pin'),
('Noix de pin', 'noix de pins'),
('Noix de pin', 'pine nuts'),
('Graines de tournesol', 'graines de tournesol'),
('Graines de tournesol', 'sunflower seeds'),
('Raisins secs', 'raisins secs'),
('Raisins secs', 'raisins sec'),
('Canneberges séchées', 'canneberges sechees'),
('Canneberges séchées', 'dried cranberries'),
('Canneberges séchées', 'cranberries'),
('Noix mélangées', 'noix au choix'),
('Noix mélangées', 'noix melangees'),
('Noix mélangées', 'mixed nuts'),
('Croustilles de pita', 'chips de pita'),
('Croustilles de pita', 'pita chips'),
('Croustilles de pita', 'croustilles de pita'),
('Eau', 'eau'),
('Eau', 'water'),
('Gingembre moulu', 'gingembre moulu'),
('Gingembre moulu', 'gingembre en poudre'),
('Gingembre moulu', 'ground ginger'),
('Gingembre moulu', 'ginger powder'),
('Riz brun', 'riz brun'),
('Riz brun', 'riz brun a grain long'),
('Riz brun', 'riz complet'),
('Riz brun', 'brown rice'),
('Riz brun', 'long grain brown rice'),
('Huile de truffe', 'huile de truffe'),
('Huile de truffe', 'huile a la truffe'),
('Huile de truffe', 'huile de truffe blanche'),
('Huile de truffe', 'truffle oil'),
('Huile de truffe', 'white truffle oil'),
('Poivron jaune', 'poivron jaune'),
('Poivron jaune', 'poivrons jaunes'),
('Poivron jaune', 'poivron orange'),
('Poivron jaune', 'poivrons oranges'),
('Poivron jaune', 'yellow bell pepper'),
('Poivron jaune', 'yellow bell peppers'),
('Poivron jaune', 'yellow pepper'),
('Poivron jaune', 'yellow peppers'),
('Poivron jaune', 'orange bell pepper'),
('Poivron jaune', 'orange bell peppers'),
('Poivron jaune', 'orange pepper'),
('Vinaigre de vin blanc', 'vinaigre de vin blanc'),
('Vinaigre de vin blanc', 'white wine vinegar'),
('Pâte de cari vert', 'pate de cari vert'),
('Pâte de cari vert', 'pate de curry vert'),
('Pâte de cari vert', 'green curry paste'),
('Pâte de cari vert', 'thai green curry paste'),
('Tortillas de maïs', 'tortillas de mais'),
('Tortillas de maïs', 'tortilla de mais'),
('Tortillas de maïs', 'corn tortillas'),
('Tortillas de maïs', 'corn tortilla'),
('Farine de pois chiches', 'farine de pois chiches'),
('Farine de pois chiches', 'farine de pois chiche'),
('Farine de pois chiches', 'chickpea flour'),
('Farine de pois chiches', 'gram flour'),
('Farine de pois chiches', 'besan'),
('Farine de maïs', 'farine de mais'),
('Farine de maïs', 'semoule de mais'),
('Farine de maïs', 'cornmeal'),
('Farine de maïs', 'corn meal'),
('Farine de maïs', 'masa harina'),
('Eau de coco', 'eau de coco'),
('Eau de coco', 'coconut water'),
('Feuilles de lime kaffir', 'feuilles de lime kaffir'),
('Feuilles de lime kaffir', 'feuille de lime kaffir'),
('Feuilles de lime kaffir', 'feuilles de lime'),
('Feuilles de lime kaffir', 'feuilles de kaffir'),
('Feuilles de lime kaffir', 'kaffir lime leaves'),
('Feuilles de lime kaffir', 'kaffir lime leaf'),
('Feuilles de lime kaffir', 'makrut lime leaves'),
('Feuilles de lime kaffir', 'makrut lime leaf'),
('Feuilles de lime kaffir', 'lime leaves'),
('Citronnelle', 'citronnelle'),
('Citronnelle', 'tige de citronnelle'),
('Citronnelle', 'tiges de citronnelle'),
('Citronnelle', 'lemongrass'),
('Citronnelle', 'lemon grass'),
('Citronnelle', 'lemongrass stalk'),
('Citronnelle', 'lemongrass stalks'),
('Mélasse de grenade', 'melasse de grenade'),
('Mélasse de grenade', 'pomegranate molasses'),
('Pois mange-tout', 'pois mange tout'),
('Pois mange-tout', 'pois mangetout'),
('Pois mange-tout', 'pois sucres'),
('Pois mange-tout', 'pois sugar snap'),
('Pois mange-tout', 'snow peas'),
('Pois mange-tout', 'snap peas'),
('Pois mange-tout', 'sugar snap peas'),
('Yogourt végétal', 'yogourt vegetal'),
('Yogourt végétal', 'yogourt vegetalien'),
('Yogourt végétal', 'yogourt vegane'),
('Yogourt végétal', 'yogourt de coco'),
('Yogourt végétal', 'yogourt a la noix de coco'),
('Yogourt végétal', 'coconut yogurt'),
('Yogourt végétal', 'vegan yogurt'),
('Yogourt végétal', 'plant based yogurt'),
('Yogourt végétal', 'dairy free yogurt'),
('Sauce de poisson végétalienne', 'sauce de poisson vegetalienne'),
('Sauce de poisson végétalienne', 'sauce de poisson vegane'),
('Sauce de poisson végétalienne', 'sauce de poisson vegetarienne'),
('Sauce de poisson végétalienne', 'sauce poisson vegetalienne'),
('Sauce de poisson végétalienne', 'vegan fish sauce'),
('Sauce de poisson végétalienne', 'vegetarian fish sauce'),
('Chipotle en poudre', 'chipotle en poudre'),
('Chipotle en poudre', 'piment chipotle moulu'),
('Chipotle en poudre', 'chipotle moulu'),
('Chipotle en poudre', 'chipotle powder'),
('Chipotle en poudre', 'chipotle chili powder'),
('Chipotle en poudre', 'ground chipotle'),
('Crème de champignons (conserve)', 'creme de champignons'),
('Crème de champignons (conserve)', 'soupe creme de champignons'),
('Crème de champignons (conserve)', 'cream of mushroom soup'),
('Crème de champignons (conserve)', 'cream of mushroom'),
('Crème de champignons (conserve)', 'condensed cream of mushroom soup'),
('Galettes de riz', 'galettes de riz'),
('Galettes de riz', 'galette de riz'),
('Galettes de riz', 'feuilles de riz'),
('Galettes de riz', 'feuille de riz'),
('Galettes de riz', 'papier de riz'),
('Galettes de riz', 'rice paper'),
('Galettes de riz', 'rice paper wrappers'),
('Galettes de riz', 'rice paper sheets'),
('Galettes de riz', 'spring roll wrappers'),
('Base de bouillon (pâte)', 'base de bouillon'),
('Base de bouillon (pâte)', 'base de bouillon de legumes'),
('Base de bouillon (pâte)', 'pate de bouillon'),
('Base de bouillon (pâte)', 'concentre de bouillon'),
('Base de bouillon (pâte)', 'concentre de bouillon de legumes'),
('Base de bouillon (pâte)', 'bouillon paste'),
('Base de bouillon (pâte)', 'vegetable bouillon paste'),
('Base de bouillon (pâte)', 'better than bouillon'),
('Base de bouillon (pâte)', 'vegetable bouillon base'),
('Romarin frais', 'romarin frais'),
('Romarin frais', 'branche de romarin'),
('Romarin frais', 'branches de romarin'),
('Romarin frais', 'brin de romarin'),
('Romarin frais', 'brins de romarin'),
('Romarin frais', 'fresh rosemary'),
('Romarin frais', 'rosemary sprig'),
('Romarin frais', 'rosemary sprigs'),
('Romarin frais', 'sprigs of rosemary'),
('Sauge séchée', 'sauge sechee'),
('Sauge séchée', 'sauge moulue'),
('Sauge séchée', 'dried sage'),
('Sauge séchée', 'ground sage'),
('Sauge séchée', 'rubbed sage'),
('Menthe séchée', 'menthe sechee'),
('Menthe séchée', 'dried mint'),
('Vinaigre balsamique blanc', 'vinaigre balsamique blanc'),
('Vinaigre balsamique blanc', 'white balsamic vinegar'),
('Vinaigre balsamique blanc', 'balsamique blanc'),
('Piment doux', 'piment doux'),
('Piment doux', 'piments doux'),
('Piment doux', 'piment chili doux'),
('Piment doux', 'piments chili doux'),
('Piment doux', 'mild chili'),
('Piment doux', 'mild chili pepper'),
('Piment doux', 'mild chilies')
)
insert into ingredient_aliases (ingredient_id, household_id, alias) select i.id, null, c.alias from c join ingredients i on i.household_id is null and i.name = c.name on conflict do nothing;
